### ISSUE TITLE
App can't c touch & pen touch

### ISSUE THREAD

**Issue by chistine1018** [koreader/koreader#10477]
* KOReader version:2023.04(Latest)
* Device: MobiScribe Wave(Andr12)

#### Issue
My device can install KOReader,but when open file can't touch.

I also see similar issue in https://github.com/koreader/android-luajit-launcher/pull/229.

##### `crash.log` (if applicable)
Failed to open /storage/emulated/0/koreader/settings/vocabulary_builder.sqlite3-shm to set project id.: No such file or directory
W  Failed to update quota type for /storage/emulated/0/koreader/settings/vocabulary_builder.sqlite3-shm
java.io.IOException: Failed to update quota type for /storage/emulated/0/koreader/settings/vocabulary_builder.sqlite3-shm
at android.os.storage.StorageManager.updateExternalStorageFileQuotaType(StorageManager.java:2596)
at com.android.providers.media.MediaProvider.updateQuotaTypeForFileInternal(MediaProvider.java:647)
at com.android.providers.media.MediaProvider.lambda$onFileCreatedForFuse$12(MediaProvider.java:1304)
at com.android.providers.media.MediaProvider.$r8$lambda$qQ2SL_xqs-9v4mCYUB_TrDraYeg(Unknown Source:0)
at com.android.providers.media.MediaProvider$$ExternalSyntheticLambda11.run(Unknown Source:4)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by pazos** [comment]
Please read https://github.com/koreader/koreader/issues/8482 and provide feedback (if any) there. Thanks!
