### ISSUE TITLE
Crash when attempting to connect to Calibre server

### ISSUE THREAD

**Issue by TheLastZombie** [koreader/koreader#10485]
* KOReader version: 2023.04
* Device: reMarkable 2 (2.15.1.1189)

#### Issue

When attempting to connect to a Calibre server, KOReader crashes with the message "attempt to perform arithmetic on a string value" [here](https://github.com/koreader/koreader/blob/v2023.04/frontend/util.lua#L857). (The below logs show line 860 because I added some debug logging to the code.) In my case, the value of `stage[k]` is `ERROR`.

KOReader's logs are attached below. At the same time, Calibre also displays a pop-up with the following log:

<details>
  <summary>Calibre log</summary>

```
calibre, version 6.17.0
ERROR: Error: Error communicating with device

Device responded with incorrect information

Traceback (most recent call last):
  File "calibre/gui2/device.py", line 104, in run
  File "calibre/gui2/device.py", line 522, in _get_device_information
  File "calibre/devices/smart_device_app/driver.py", line 59, in _synchronizer
  File "calibre/devices/smart_device_app/driver.py", line 1282, in free_space
  File "calibre/devices/smart_device_app/driver.py", line 59, in _synchronizer
  File "calibre/devices/smart_device_app/driver.py", line 653, in _call_client
  File "calibre/devices/smart_device_app/driver.py", line 695, in _receive_from_client
calibre.devices.errors.ControlError: Device responded with incorrect information
```
</details>

#### Steps to reproduce

1. Connect a reMarkable 2 with KOReader via USB to a device with Calibre
2. Open Calibre
3. Start Calibre's device connection server if not configured to do so automatically
4. Open KOReader
5. Within KOReader, tap on the tools icon, then on "Calibre" -> "Connect"

##### `crash.log` (if applicable)

<details>
  <summary>crash.log</summary>

```
Original fb settings: bitdepth = 16, rotation = 0
Switching fb bitdepth to 8bpp & rotation to Portrait
[FBInk] Detected a reMarkable 2 (Zero Sugar)
[FBInk] This device does not support HW inversion
[FBInk] Running under the rm2fb compatibility shim (version 0.1), functionality may be limited
[FBInk] Clock tick frequency appears to be 100 Hz
[FBInk] Screen density set to 226 dpi
[FBInk] Variable fb info: 1404x1872, 16bpp @ rotation: 0 (Upright, 0°)
[FBInk] Fixed fb info: ID is "mxcfb", length of fb mem: 5256576 bytes & line length: 2808 bytes
[FBInk] Fontsize set to 24x24 (IBM base glyph size: 8x8)
[FBInk] Line length: 58 cols, Page size: 78 rows
[FBInk] Pen colors set to #000000 for the foreground and #FFFFFF for the background
[FBDepth] Screen is 1404x1872 (1404x1872 addressable, fb says 1404x1872)
[FBDepth] Buffer is mapped for 5256576 bytes with a scanline stride of 2808 bytes
[FBDepth] Switching fb to 8bpp @ rotation 1 . . .
Updating bitdepth from 16bpp to 8bpp
Sanitizing grayscale flag for 8bpp
Updating rotation from 0 (Upright, 0°) to 1 (Clockwise, 90°)
Bitdepth is now 8bpp (grayscale: 1) @ rotate: 1 (Clockwise, 90°)
[FBDepth] Screen is 1404x1872 (1404x1872 addressable, fb says 1404x1872)
[FBDepth] Buffer is mapped for 5256576 bytes with a scanline stride of 2808 bytes
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 05/25/23-15:56:10
 [*] Version: v2023.04

ffi.load: libs/libutf8proc.so.2
ffi.load: blitbuffer
05/25/23-15:56:10 INFO  Starting reMarkable 2.0 
05/25/23-15:56:10 INFO  Oxide running?: false 
ERROR: ld.so: object '/opt/lib/librm2fb_client.so.1' from LD_PRELOAD cannot be preloaded (internal error): ignored.
[ko-input] Forked off fake event generator (pid: 17928)
05/25/23-15:56:10 INFO  initializing for device reMarkable 2.0 
05/25/23-15:56:10 INFO  framebuffer resolution: {
  h = 1872,
  w = 1404
} --[[table: 0x76672a70]] 
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libharfbuzz.so.0
ffi.load: libs/libzstd.so.1
05/25/23-15:56:11 INFO  Loading plugins from directory: plugins 
ffi.load: sqlite3
05/25/23-15:56:19 INFO  calibre info loaded from disk in 33.000 milliseconds: 238 books. 0 pruned 
ffi.load: libs/libczmq.so.1
ffi.load: libs/libzmq.so.4
ffi.load: libs/libczmq.so.1
05/25/23-15:56:19 INFO  connecting to calibre @ 192.168.178.35:9090 
./luajit: frontend/util.lua:860: attempt to perform arithmetic on a string value
stack traceback:
        frontend/util.lua:860: in function 'diskUsage'
        plugins/calibre.koplugin/wireless.lua:43: in function 'getFreeSpace'
        plugins/calibre.koplugin/wireless.lua:474: in function 'getFreeSpace'
        plugins/calibre.koplugin/wireless.lua:336: in function 'onReceiveJSON'
        plugins/calibre.koplugin/wireless.lua:141: in function 'receiveCallback'
        frontend/ui/message/streammessagequeue.lua:86: in function '(for generator)'
        frontend/ui/uimanager.lua:1424: in function 'processZMQs'
        frontend/ui/uimanager.lua:1487: in function 'handleInput'
        frontend/ui/uimanager.lua:1559: in function 'run'
        ./reader.lua:319: in main chunk
        [C]: at 0x000140f1
!!!!
ERROR: ld.so: object '/opt/lib/librm2fb_client.so.1' from LD_PRELOAD cannot be preloaded (internal error): ignored.
Uh oh, something went awry... (Crash n°1: 05/25/23 @ 15:56:24)
ERROR: ld.so: object '/opt/lib/librm2fb_client.so.1' from LD_PRELOAD cannot be preloaded (internal error): ignored.
ERROR: ld.so: object '/opt/lib/librm2fb_client.so.1' from LD_PRELOAD cannot be preloaded (internal error): ignored.
Running on Linux 5.4.70-v1.2.5-rm11x (#1 SMP PREEMPT Sun Oct 23 20:48:32 UTC 2022)
Attempting to restart KOReader . . .
!!!!
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 05/25/23-15:56:39
 [*] Version: v2023.04

ffi.load: libs/libutf8proc.so.2
ffi.load: blitbuffer
05/25/23-15:56:39 INFO  Starting reMarkable 2.0 
05/25/23-15:56:39 INFO  Oxide running?: false 
ERROR: ld.so: object '/opt/lib/librm2fb_client.so.1' from LD_PRELOAD cannot be preloaded (internal error): ignored.
[ko-input] Forked off fake event generator (pid: 17957)
05/25/23-15:56:39 INFO  initializing for device reMarkable 2.0 
05/25/23-15:56:39 INFO  framebuffer resolution: {
  h = 1872,
  w = 1404
} --[[table: 0x7655c7a0]] 
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libharfbuzz.so.0
ffi.load: libs/libzstd.so.1
05/25/23-15:56:40 INFO  Loading plugins from directory: plugins 
ffi.load: sqlite3
05/25/23-15:56:49 INFO  no dialog left to show 
05/25/23-15:56:49 INFO  Tearing down UIManager with exit code: 0 
[ko-input] Closed input device with fd: 7 @ idx: 3
[ko-input] Closed input device with fd: 6 @ idx: 2
[ko-input] Closed input device with fd: 5 @ idx: 1
[ko-input] Closed input device with fd: 3 @ idx: 0
Restoring original fb bitdepth @ 16bpp & rotation @ 0
[FBInk] Detected a reMarkable 2 (Zero Sugar)
[FBInk] This device does not support HW inversion
[FBInk] Running under the rm2fb compatibility shim (version 0.1), functionality may be limited
[FBInk] Clock tick frequency appears to be 100 Hz
[FBInk] Screen density set to 226 dpi
[FBInk] Variable fb info: 1404x1872, 16bpp @ rotation: 0 (Upright, 0°)
[FBInk] Fixed fb info: ID is "mxcfb", length of fb mem: 5256576 bytes & line length: 2808 bytes
[FBInk] Fontsize set to 24x24 (IBM base glyph size: 8x8)
[FBInk] Line length: 58 cols, Page size: 78 rows
[FBInk] Pen colors set to #000000 for the foreground and #FFFFFF for the background
[FBDepth] Screen is 1404x1872 (1404x1872 addressable, fb says 1404x1872)
[FBDepth] Buffer is mapped for 5256576 bytes with a scanline stride of 2808 bytes
[FBDepth] Current bitdepth is already 16bpp!
[FBDepth] Current rotation is already 0!
```
</details>

**Comment by NiLuJe** [comment]
Can you add some more debugging to see on what kind of path it's returning an error? 

Or is df -k just plain unusable on rM?

At a very quick glance, the error handling doe slook shady (e.g., I'd possibly return `nil, output` in the erro case).

**Comment by TheLastZombie** [comment]
> Or is df -k just plain unusable on rM?

Ah, I know what's happening. The full output of the `df -k` command in `util.diskUsage` is:

```
ERROR: ld.so: object '/opt/lib/librm2fb_client.so.1' from LD_PRELOAD cannot be preloaded (internal error): ignored.
6884064 2955980 3558676
```

AFAIK this error is rather a warning and can be ignored, but KOReader tries to parse that instead of the numbers in the next line (which is where the value of `ERROR` came from - `ERROR: ld.so`).

**Comment by NiLuJe** [comment]
I'm mildly intrigued by the root cause of the ld error, though, but that's probably a question best left to the Toltec guys ;).

**Comment by Eeems** [comment]
> I'm mildly intrigued by the root cause of the ld error, though, but that's probably a question best left to the Toltec guys ;).

rm2fb is loaded using a LD_PRELOAD. Toltec makes use of entware as a base, so we don't have to repackage a bunch of stuff. Those packages are built against their own libc, since it needs to be all self-contained to make sure it works no matter the device. This error happens when you try to run one of those executables while the LD_PRELOAD environment variable is set.

You can get around it by clearing the LD_PRELOAD environment variable before calling those executables, but that could be a problem if someone is trying to use LD_PRELOAD for something other than rm2fb.

Another option would be to force it to use the built-in `df` provided by busybox, instead of the entware one on the path.

**Comment by NiLuJe** [comment]
I'm still midly curious about the technical limitations of preloading a library built with another libc, though. Is the actual issue that they're built with a different ELF interpreter set in the headers (or something)?

**Comment by Eeems** [comment]
> I'm still mildly curious about the technical limitations of preloading a library built with another libc, though (because I'm pretty sure I've done that safely in the past; e.g., for snooping over custom ioctl via an interposed ioctl wrapper). Is the actual issue that they're built with a different ELF interpreter set in the headers (or something to that effect)?

Right, something like that. It's a different ld-linux.so between the two of them.

```shell
reMarkable: ~/ file /opt/bin/python3.10
/opt/bin/python3.10: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /opt/lib/ld-linux.so.3, for GNU/Linux 3.2.0, stripped
reMarkable: ~/ file /bin/busybox.nosuid 
/bin/busybox.nosuid: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, BuildID[sha1]=e999e562603b8689d61babd127d41328dd51facf, for GNU/Linux 3.2.0, stripped
```

**Comment by NiLuJe** [comment]
Which, on the flip side, is also what allows you to easily isolate stuff to a specific glibc/loader, okay, makes sense, thanks ;o).
