### ISSUE TITLE
Samsung: app gets stuck reloading when partial rendering is enabled

### ISSUE THREAD

**Issue by arpanghosh8453** [koreader/koreader#12099]
* KOReader version: 2024.04 and 2024.04-209
* Device: Samsung M32

#### Issue

Android app gets stuck and stops responding indefinitely showing the following icon on top left corner. After a while android prompts with a stop this application message, I tried waiting, but it did not work. This thing gets triggered only when I perform an action which requires reloading the whole document, as in changing font, changing orientation or anything of that kind. 
![partial_rendering_4](https://github.com/koreader/koreader/assets/26424944/7baf16a3-a0c8-43fd-b473-08ef02d018f4)

Is anyone facing the same issue with Android? 

##### `crash.log` (if applicable)

```java
06-26 18:57:14.466 V/NativeGlue( 9953): NativeWindowResized: 0xb40000793851adc0 -- 0xb400007889ca8010
06-26 18:57:14.469 E/Resources( 9953): An exception occurred : 
06-26 18:57:14.469 E/Resources( 9953): java.util.concurrent.ExecutionException: android.content.res.Resources$NotFoundException: Drawable org.koreader.launcher:drawable/splash_icon with resource ID #0x7f070066
06-26 18:57:14.469 E/Resources( 9953): 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
06-26 18:57:14.469 E/Resources( 9953): 	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
06-26 18:57:14.469 E/Resources( 9953): 	at android.content.res.Resources.fetchDrawableFromFutureCache(Resources.java:2841)
06-26 18:57:14.469 E/Resources( 9953): 	at android.content.res.Resources.loadDrawable(Resources.java:1067)
06-26 18:57:14.469 E/Resources( 9953): 	at android.content.res.Resources.getDrawableForDensity(Resources.java:1051)
06-26 18:57:14.469 E/Resources( 9953): 	at android.content.res.Resources.getDrawable(Resources.java:990)
06-26 18:57:14.469 E/Resources( 9953): 	at android.content.Context.getDrawable(Context.java:823)
06-26 18:57:14.469 E/Resources( 9953): 	at androidx.core.content.ContextCompat$Api21Impl.getDrawable(ContextCompat.java:1)
06-26 18:57:14.469 E/Resources( 9953): 	at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:2)
06-26 18:57:14.469 E/Resources( 9953): 	at org.koreader.launcher.MainActivity.drawSplashScreen(MainActivity.kt:3)
06-26 18:57:14.469 E/Resources( 9953): 	at org.koreader.launcher.MainActivity.surfaceChanged(MainActivity.kt:5)
06-26 18:57:14.469 E/Resources( 9953): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4119)
06-26 18:57:14.469 E/Resources( 9953): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3116)
06-26 18:57:14.469 E/Resources( 9953): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10885)
```

Full log file attached. 
[crash.log](https://github.com/user-attachments/files/15989067/crash.log)

**Comment by NiLuJe** [comment]
That attachment is empty ;).

**Comment by pazos** [comment]
> Android app gets stuck and stops responding indefinitely showing the following icon on top left corner. After a while android prompts with a stop this application message

That's an ANR. It means there're pending events on the input queue. You can try to reproduce the same thing without touching the screen while that icon is present.

**Comment by arpanghosh8453** [comment]
@pazos Yes, but that state is supposed to be temporary ( for a few seconds/minutes ) but it's in that state forever afterward and ultimately android kills the app for not responding too long. 

@NiLuJe Sorry, I lost the old file, but I have reperformed the bug and here is the file : [crash.log](https://github.com/user-attachments/files/16006741/crash.log)

**Comment by NiLuJe** [comment]
What kind of book are you trying this on?

**Comment by arpanghosh8453** [comment]
@NiLuJe These are the exact same files from my Kobo device. I copied .kepub.epub files so the files stays in sync (progress sync). Is that a problem? The files are very small, and 300-400 page ebooks. Consider this a sample : https://www.goodreads.com/book/show/6969361-2-states

**Comment by ejoejoejo** [comment]
I have observed the same bug as reported by arpanghosh8453 since the introduction of partial rendering, on my two Samsung devices. But work around it by disabling partial rendering.
I had this problem with 100 % of my epubs, the ones I opened that means 😀

**Comment by arpanghosh8453** [comment]
@ejoejoejo Yes! That indeed solves the issue. @NiLuJe Looks like something is up with the partial rendering on Androids (although my A7 tab worked fine with 2024.04). If I disable the partial rendering and make it the default settings, I still need to disable it for individual books whenever I open a new book.

**Comment by mergen3107** [comment]
@arpanghosh8453 
Long press on the setting to make it default :D

**Comment by mergen3107** [comment]
I turned this feature off because it is only for epubs, and I read in fb2 (wanted consistency). However, I didn’t have troubles like this on Onyx Boox Kon-Tiki 2. Let me try it sometime later, maybe I could get some pidcat logs

**Comment by arpanghosh8453** [comment]
> @arpanghosh8453 Long press on the setting to make it default :D

I think it's because of device sync. The books that I opened on my Kobo reverts back to the settings there. Brand new books follow default settings.

**Comment by ejoejoejo** [comment]
When I set the partial rendering default it is persistent.

**Comment by arpanghosh8453** [comment]
> When I set the partial rendering default on Android it is persistent.

I understand now, that was because I copied the .sdr sidecar files when copying the ebooks with all the settings from my kobo.

**Comment by mergen3107** [comment]
@arpanghosh8453 
You can try overriding this setting with directory defaults file in settings folder. Setting name itself is in settings.reader.lua

**Comment by pazos** [comment]
> I have observed the same bug as reported by arpanghosh8453 since the introduction of partial rendering, on my two Samsung devices. But work around it by disabling partial rendering.
I had this problem with 100 % of my epubs, the ones I opened that means 😀

Yup, almost there :)

This is likely our bug, or at least something we can workaround.

Please reproduce and catch logs with `pidcat`.

**Comment by ejoejoejo** [comment]
I am new to this. I installed the SDK (Linux), Connect my phone to the laptop, allow access on its screen, do a 5 minute prayer, then I run python3 ./pidcat.py org.koreader.launcher. This is what I get:

* daemon not running; starting now at tcp:5037
* daemon started successfully
- waiting for device -

Now what?

**Comment by Frenzie** [comment]
You probably have to enable USB debugging. It might be hidden in some developer options settings which doesn't show up unless you tap a few times on the Android version in "about".

**Comment by ejoejoejo** [comment]
[partial_render.log](https://github.com/user-attachments/files/16034276/partial_render.log)

Thanks Frans, that helped. So I re-ran pidcat, piped the output to attached file, started koreader (latest OTA update), changed the fontsize, thereby creating a crash, and terminated the app when Android said it was taking too long to react. Is that Okay?

**Comment by pazos** [comment]
>Is that Okay?

Mostly, thanks!

The error is printed, at least.

```logcat
KOReader  I  Restoring user input handling
reader.launcher  I Thread[3,tid=3586,WaitingInMainSignalCatcherLoop,Thread*=0xb400007bea446400,peer=0x132401e8,"Signal Catcher"]: reacting to signal 3'

As timestamps aren't printed I'm not sure if one happens just after ther other. Anyhow, it doesn't seem enough time to trigger an ANR. A few lines above I see:

```logcat
NativeGlue  V  NativeWindowResized: 0xb400007bea4d3ec0 -- 0xb400007b74789010
KOReader  I  Restoring user input handling
KOReader  I  Inhibiting user input
```

Not sure what happens there to restore user input handling and inhibit it just after that. Any input event that gets queued 
in that time frame and doesn't get drained from there will trigger an ANR.

No idea why I can't reproduce here.

**Comment by dingliu** [comment]
I just came across this issue and fixed with disabling partial rendering.

> Long press on the setting to make it default :D

Thanks @mergen3107 for sharing this. 🙏

- KOReader version: 2024.11
- Device: Samsung Galaxy Tab S6 Lite
- OS: Android 13, One UI 5.1.1
