### ISSUE TITLE
KOReader Nightly Crash on my Android Tablet

### ISSUE THREAD

**Issue by winstonma** [koreader/koreader#12141]
* KOReader version: v2024.04.222
* Device: Redmi Pad SE

#### Issue
I installed KOReader 2024.04, opened a book, then choose update server to development channel. Then after the update KOReader just close after the book is reopened.

I didn't see any problem in KOReader 2024.04 but it crashes after the v2024.04.222 is installed

#### Steps to reproduce
As mentioned above.

##### `crash.log` (if applicable)
I couldn't find the crash.log but here is the log captured in logcat

```
07-06 15:51:33.038 11617 11829 E chromium: [0706/155133.038372:ERROR:ssl_client_socket_impl.cc(878)] handshake failed; returned -1, SSL error code 1, net_error -101
07-06 15:51:33.044 11617 11829 E chromium: [0706/155133.044586:ERROR:ssl_client_socket_impl.cc(878)] handshake failed; returned -1, SSL error code 1, net_error -100
07-06 15:51:33.045 11617 11829 I cr_CronetUrlRequestContext: destroyNativeStreamLocked org.chromium.net.impl.CronetBidirectionalStream@8f744c5
07-06 15:51:33.073 11617 11814 W AsyncOperation: operation=SyncActivityControlsSettingsInternalOperation, opStatusCode=7 [CONTEXT service_id=220 ]
07-06 15:51:33.073 11617 11814 W AsyncOperation: OperationException[Status{statusCode=Downloading settings failed!, resolution=null}]
07-06 15:51:33.073 11617 11814 W AsyncOperation: 	at dngn.f(:com.google.android.gms@242335038@24.23.35 (190400-646585959):192)
07-06 15:51:33.073 11617 11814 W AsyncOperation: 	at boey.hj(:com.google.android.gms@242335038@24.23.35 (190400-646585959):1)
07-06 15:51:33.073 11617 11814 W AsyncOperation: 	at bofh.run(:com.google.android.gms@242335038@24.23.35 (190400-646585959):97)
07-06 15:51:33.073 11617 11814 W AsyncOperation: 	at emsz.run(:com.google.android.gms@242335038@24.23.35 (190400-646585959):21)
07-06 15:51:33.073 11617 11814 W AsyncOperation: 	at angs.c(:com.google.android.gms@242335038@24.23.35 (190400-646585959):50)
07-06 15:51:33.073 11617 11814 W AsyncOperation: 	at angs.run(:com.google.android.gms@242335038@24.23.35 (190400-646585959):76)
07-06 15:51:33.073 11617 11814 W AsyncOperation: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
07-06 15:51:33.073 11617 11814 W AsyncOperation: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
07-06 15:51:33.073 11617 11814 W AsyncOperation: 	at anmg.run(:com.google.android.gms@242335038@24.23.35 (190400-646585959):8)
07-06 15:51:33.073 11617 11814 W AsyncOperation: 	at java.lang.Thread.run(Thread.java:1012)
07-06 15:51:33.073 11617 11814 W AsyncOperation: Caused by: gcaa: UNAVAILABLE
07-06 15:51:33.073 11617 11814 W AsyncOperation: 	at gcwe.b(:com.google.android.gms@242335038@24.23.35 (190400-646585959):162)
07-06 15:51:33.073 11617 11814 W AsyncOperation: 	at fjwk.b(:com.google.android.gms@242335038@24.23.35 (190400-646585959):64)
07-06 15:51:33.073 11617 11814 W AsyncOperation: 	at dnkv.n(:com.google.android.gms@242335038@24.23.35 (190400-646585959):395)
07-06 15:51:33.073 11617 11814 W AsyncOperation: 	at dnkv.e(:com.google.android.gms@242335038@24.23.35 (190400-646585959):32)
07-06 15:51:33.073 11617 11814 W AsyncOperation: 	at dngm.a(:com.google.android.gms@242335038@24.23.35 (190400-646585959):9)
07-06 15:51:33.073 11617 11814 W AsyncOperation: 	at dxoo.a(:com.google.android.gms@242335038@24.23.35 (190400-646585959):3)
07-06 15:51:33.073 11617 11814 W AsyncOperation: 	at dxou.a(:com.google.android.gms@242335038@24.23.35 (190400-646585959):158)
07-06 15:51:33.073 11617 11814 W AsyncOperation: 	at emsv.a(:com.google.android.gms@242335038@24.23.35 (190400-646585959):13)
07-06 15:51:33.073 11617 11814 W AsyncOperation: 	at etvv.d(:com.google.android.gms@242335038@24.23.35 (190400-646585959):3)
07-06 15:51:33.073 11617 11814 W AsyncOperation: 	at etvx.run(:com.google.android.gms@242335038@24.23.35 (190400-646585959):42)
07-06 15:51:33.073 11617 11814 W AsyncOperation: 	... 6 more
07-06 15:51:33.073 11617 11814 W AsyncOperation: Caused by: m.ki: Exception in BidirectionalStream: net::ERR_CONNECTION_CLOSED, ErrorCode=5, InternalErrorCode=-100, Retryable=true
07-06 15:51:33.073 11617 11814 W AsyncOperation: 	at org.chromium.net.impl.CronetBidirectionalStream.onError(:com.google.android.gms.dynamite_cronetdynamite@242335038@24.23.35 (190400-0):28)
07-06 15:51:33.073 11617 11814 W FacsCacheGmsModule: Operation 'SyncActivityControlsSettingsInternalOperation' failed with status '7'!
07-06 15:51:33.076 12051 12103 W AsyncOperation: operation=GetActivityControlsSettingsOperation, opStatusCode=7 [CONTEXT service_id=202 ]
07-06 15:51:33.076 12051 12103 W AsyncOperation: OperationException[Status{statusCode=Internal sync API failure!, resolution=null}]
07-06 15:51:33.076 12051 12103 W AsyncOperation: 	at dnfq.i(:com.google.android.gms@242335038@24.23.35 (190400-646585959):27)
07-06 15:51:33.076 12051 12103 W AsyncOperation: 	at dnfy.f(:com.google.android.gms@242335038@24.23.35 (190400-646585959):137)
07-06 15:51:33.076 12051 12103 W AsyncOperation: 	at boey.hj(:com.google.android.gms@242335038@24.23.35 (190400-646585959):1)
07-06 15:51:33.076 12051 12103 W AsyncOperation: 	at bofh.run(:com.google.android.gms@242335038@24.23.35 (190400-646585959):97)
07-06 15:51:33.076 12051 12103 W AsyncOperation: 	at emsz.run(:com.google.android.gms@242335038@24.23.35 (190400-646585959):21)
07-06 15:51:33.076 12051 12103 W AsyncOperation: 	at angs.c(:com.google.android.gms@242335038@24.23.35 (190400-646585959):50)
07-06 15:51:33.076 12051 12103 W AsyncOperation: 	at angs.run(:com.google.android.gms@242335038@24.23.35 (190400-646585959):76)
07-06 15:51:33.076 12051 12103 W AsyncOperation: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
07-06 15:51:33.076 12051 12103 W AsyncOperation: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
07-06 15:51:33.076 12051 12103 W AsyncOperation: 	at anmg.run(:com.google.android.gms@242335038@24.23.35 (190400-646585959):8)
07-06 15:51:33.076 12051 12103 W AsyncOperation: 	at java.lang.Thread.run(Thread.java:1012)
07-06 15:51:33.076 12051 12103 W AsyncOperation: Caused by: alqy: 7: Downloading settings failed!
07-06 15:51:33.076 12051 12103 W AsyncOperation: 	at amow.a(:com.google.android.gms@242335038@24.23.35 (190400-646585959):15)
07-06 15:51:33.076 12051 12103 W AsyncOperation: 	at alwu.b(:com.google.android.gms@242335038@24.23.35 (190400-646585959):11)
07-06 15:51:33.076 12051 12103 W AsyncOperation: 	at aulo.c(:com.google.android.gms@242335038@24.23.35 (190400-646585959):10)
07-06 15:51:33.076 12051 12103 W AsyncOperation: 	at aumf.hf(:com.google.android.gms@242335038@24.23.35 (190400-646585959):51)
07-06 15:51:33.076 12051 12103 W AsyncOperation: 	at oxh.onTransact(:com.google.android.gms@242335038@24.23.35 (190400-646585959):74)
07-06 15:51:33.076 12051 12103 W AsyncOperation: 	at android.os.Binder.execTransactInternal(Binder.java:1501)
07-06 15:51:33.076 12051 12103 W AsyncOperation: 	at android.os.Binder.execTransact(Binder.java:1440)
07-06 15:51:33.078 12051 12103 W FacsCacheGmsModule: Operation 'GetActivityControlsSettingsOperation' failed with status '7'!
07-06 15:51:33.081  9871  9973 W A       : Can't update WAA status for Mavatar!
07-06 15:51:33.081  9871  9973 W A       : com.google.android.gms.common.api.l: 7: Internal sync API failure!
07-06 15:51:33.081  9871  9973 W A       : 	at com.google.android.gms.common.internal.a.a(PG:15)
07-06 15:51:33.081  9871  9973 W A       : 	at com.google.android.gms.common.api.internal.dd.a(PG:13)
07-06 15:51:33.081  9871  9973 W A       : 	at com.google.android.gms.facs.cache.i.c(PG:35)
07-06 15:51:33.081  9871  9973 W A       : 	at com.google.android.gms.facs.cache.a.b.dispatchTransaction(PG:79)
07-06 15:51:33.081  9871  9973 W A       : 	at com.google.android.a.b.onTransact(PG:13)
07-06 15:51:33.081  9871  9973 W A       : 	at android.os.Binder.execTransactInternal(Binder.java:1501)
07-06 15:51:33.081  9871  9973 W A       : 	at android.os.Binder.execTransact(Binder.java:1440)
```

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, go to `Top menu → Hamburger menu → Help → Report a bug` and tap `Enable verbose logging`. Restart as requested, then repeat the steps for your issue.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by benoit-pierre** [comment]
We need more complete logs, try enabling debug logs and see [this comment](https://github.com/koreader/koreader/issues/10395#issuecomment-1537131597) for instructions.

(Also don't cut short the version when reporting an issue, the git commit hash at the end is the most important information).

**Comment by winstonma** [comment]
@benoit-pierre  Thanks for replying

Here is the [crash.log](https://github.com/user-attachments/files/16116055/crash.log)

**Comment by winstonma** [comment]
Thank @benoit-pierre
