### ISSUE TITLE
Calibre Plugin: Empty JSON string sent on wireless connect

### ISSUE THREAD

**Issue by bbawj** [koreader/koreader#12456]
* KOReader version: v2024.07 
* Device: Pixel 4a

#### Issue
Using the built-in calibre plugin, wireless connect sends invalid data to Calibre Desktop

#### Steps to reproduce
- Start calibre desktop wireless device connection on a fixed port
- KOReader connect to IP and fixed port
- KOReader mentions successful connection
- Calibre does not show active connection. 

Calibre log:
```
Traceback (most recent call last):
  File "calibre/gui2/device.py", line 351, in detect_device
  File "calibre/devices/smart_device_app/driver.py", line 57, in _synchronizer
  File "calibre/devices/smart_device_app/driver.py", line 1052, in open
  File "calibre/devices/smart_device_app/driver.py", line 57, in _synchronizer
  File "calibre/devices/smart_device_app/driver.py", line 650, in _call_client
  File "calibre/devices/smart_device_app/driver.py", line 692, in _receive_from_client
calibre.devices.errors.ControlError: Device responded with incorrect information
```
Calibre Debug logs show:
```
SMART_DEV (   0.00:  0.002) _attach_to_port try ip address "" on port 9090
SMART_DEV (   0.94:  0.806) _startup_on_demand listening on port 9090
SMART_DEV (   0.96:  0.000) _attach_to_port try ip address "" on port 54982
SMART_DEV (   0.98:  0.000) _startup_on_demand broadcast socket listening on port 54982
SMART_DEV (   2.00:  1.003) run All IP addresses {'lo': [{'addr': '127.0.0.1', 'netmask': '255.0.0.0', 'peer': '127.0.0.1'}], 'eth0': [{'addr': '172.19.0.4', 'netmask': '255.255.0.0', 'broadcast': '172.19.255.255'}]}
SMART_DEV (  17.01: 15.004) run attempt to open device socket
SMART_DEV (  17.04:  0.017) open
SMART_DEV (  17.07:  0.001) _call_client GET_INITIALIZATION_INFO wfr True
SMART_DEV (  17.10:  0.001) _receive_from_client protocol error -- empty json string
SMART_DEV (  17.12:  0.000) _call_client other exception
SMART_DEV (  17.13:  0.000) _write_metadata_cache
SMART_DEV (  17.15:  0.000) _write_metadata_cache wrote 0 entries, purged 0 entries
Error while trying to open <calibre.devices.smart_device_app.driver.SMART_DEVICE_APP object at 0x7ffa266a0a90> (Driver: <calibre.devices.smart_device_app.driver.SMART_DEVICE_APP object at 0x7ffa266a0a90>)
```

**Comment by benoit-pierre** [comment]
I always get that error (`Device responded with incorrect information`), but the connection is successful.

Which version of calibre?

Have you tried the latest KOReader nightly?

**Comment by bbawj** [comment]
Thank you for checking this out. I tried nightly and the connection works! 

But as you said, the error still pops up in calibre logs which could be a calibre issue. Feel free to close this anyhow.

Calibre Version: v7.17.0

**Comment by pazos** [comment]
It isn't a calibre issue. It is our and relatively new. It wasn't present when the plugin was implemented.

**Comment by NiLuJe** [comment]
Haven't looked at it, but given that we've barely touched the plugin, my vote would be on a side-effect either from the json/metadata changes or the zmq update?

Given what's involved, probably the json stuff, as I don't actively test the wireless stuff (nor do I actually use it).

**Comment by benoit-pierre** [comment]
Pretty sure it's not the zmq update (the error was present before).

**Comment by pazos** [comment]
> Given what's involved, probably the json stuff, as I don't actively test the wireless stuff (nor do I actually use it).

Mm. I didn't use it for a long time, too. Last time I did was to implement the luna json parser. It worked back then.

**Comment by pazos** [comment]
I cannot reproduce on the emulator. I've  tried with automatic and manual ip/ports. Nothing.

**Comment by jrizz43** [comment]
I am having this issue with the latest build of Koreader and my kindle paperwhite gen 10. Can't get the device to show up in calibre after trying everything I can think of

**Comment by pazos** [comment]
> I always get that error (Device responded with incorrect information), but the connection is successful.

@benoit-pierre: could you check if `calibre-debug` matches OP?

 in particular

```
SMART_DEV (  17.07:  0.001) _call_client GET_INITIALIZATION_INFO wfr True
SMART_DEV (  17.10:  0.001) _receive_from_client protocol error -- empty json string
``` 

I see we're not communicating back to the server in case of a json encoding error in https://github.com/koreader/koreader/blob/17504993aeafe83bcc3b7a4657797270d6f07d71/plugins/calibre.koplugin/wireless.lua#L355-L363

Maybe we call call `self:sendJsonData("NOOP", {})` after the logger statement?


but I cannot figure out why https://github.com/koreader/koreader/blob/17504993aeafe83bcc3b7a4657797270d6f07d71/plugins/calibre.koplugin/wireless.lua#L387-L408 might end in a state that cannot be encoded by rapidjson.

**Comment by NiLuJe** [comment]
> might end in a state that cannot be encoded by rapidjson.

Is the rapidjson error we log helpful on that front?

I can't really see anything untoward at a glance, unless something can somehow be `nil` in there...

**Comment by benoit-pierre** [comment]
> > I always get that error (Device responded with incorrect information), but the connection is successful.
> 
> [@benoit-pierre](https://github.com/benoit-pierre): could you check if `calibre-debug` matches OP?

That first error from calibre is actually due to our manual & temporary TCP connection attempt before the real ZMQ one, cf. #13704.

It also increases the number of consecutive failed attempts, e.g.:
- you want to connect to calibre for the first time, click connect without setting a password: authentication failure, that's already 2 failed attempts on calibre' side because of that temporary TCP connection
- you set the password, but make a typo: another authentication failure, the counter is now 4 on calibre' side
- you fix the typo: it does not matter, the extra temporary TCP connection increases the number of failed attempts to 5, and calibre stop responding to connection attempts from that IP (with only an error trace, no UI feedback to the user) until the wireless server is restarted
