### ISSUE TITLE
2024.11 Splashscreen does not disappear

### ISSUE THREAD

**Issue by hasezoey** [koreader/koreader#12904]
* KOReader version: 2024.11 (`koreader-android-arm-v2024.11.apk`)
* Device: Tolino Vision 5

#### Issue

The Splashscreen that comes up when starting koreader never disappears.
Though if using a third-party app like Button savior(opening the side view) or view koreader in the android task-manager it is drawn correctly.
My guess is that koreader somehow changed when the window is drawn that does not work well with android 4.4.2

#### Steps to reproduce

Install the mentioned version, wait for it to be uncompressed, observe splashscreen still being there, but being able to interact with things (like the filemanager or edge gestures)
(even after restarts of koreader & device)

##### `crash.log` (if applicable)

<details>
  <summary>adb logcat output</summary>

```
--------- beginning of /dev/log/system
I/ActivityManager( 2487): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=org.koreader.launcher/.MainActivity} from pid 2639
--------- beginning of /dev/log/main
W/art     ( 2105): Could not get current activity
I/ActivityManager( 2487): Start proc org.koreader.launcher for activity org.koreader.launcher/.MainActivity: pid=2893 uid=10077 gids={50077, 3003, 1028, 1015}
I/MainActivity( 2893): loading libluajit
I/Assets  ( 2893): loading lib7z
V/NativeGlue( 2893): User FIFO already exists at `/data/data/org.koreader.launcher/files/alooper.fifo`
V/NativeThread( 2893): waiting for activity
I/DeviceInfo( 2893): MANUFACTURER: rakuten kobo inc.
I/DeviceInfo( 2893): BRAND       : rakutenkobo
I/DeviceInfo( 2893): MODEL       : tolino
I/DeviceInfo( 2893): DEVICE      : ntx_6sl
I/DeviceInfo( 2893): PRODUCT     : ntx_6sl
I/DeviceInfo( 2893): HARDWARE    : e70k00
I/Lights  ( 2893): Using TolinoNTX driver
I/TolinoNtxController( 2893): loading libioctl
V/Surface ( 2893): Using Native Content implementation
V/MainActivity( 2893): native orientation: portrait
V/EventReceiver( 2893): Filtering 3 events: 
V/EventReceiver( 2893): android.intent.action.DOWNLOAD_COMPLETE
V/EventReceiver( 2893): android.intent.action.ACTION_POWER_CONNECTED
V/EventReceiver( 2893): android.intent.action.ACTION_POWER_DISCONNECTED
V/NativeGlue( 2893): Start: 0x43b24408
V/NativeGlue( 2893): Resume: 0x43b24408
V/Timeout ( 2893): onResume: updating system timeout: 5
V/Timeout ( 2893): onResume
V/NativeGlue( 2893): InputQueueCreated: 0x43b24408 -- 0x43b261c8
D/Surface ( 2893): onAttachedToWindow()
V/NativeGlue( 2893): NativeWindowCreated: 0x43b24408 -- 0x41358d58
V/NativeThread( 2893): Activity window ready.
V/Surface ( 2893): surface changed {
V/Surface ( 2893):   width:  1264
V/Surface ( 2893):   height: 1680
V/Surface ( 2893):   format: RGB_565
V/Surface ( 2893): }
V/NativeGlue( 2893): NativeWindowResized: 0x43b24408 -- 0x41358d58
V/NativeGlue( 2893): ContentRectChanged: l=0,t=0,r=1264,b=1680
V/NativeGlue( 2893): WindowFocusChanged: 0x43b24408 -- 1
V/NativeThread( 2893): Activity gained focus.
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41359dc8,peer=0x6481e970,"Thread-71"] attached without supplying a name
V/NativeThread( 2893): Launching LuaJIT assets
V/NativeGlue( 2893): NativeWindowRedrawNeeded: 0x43b24408 -- 0x41358d58
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41359dc8,peer=0x6481f1d0,"Thread-72"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41359dc8,peer=0x6481f9c0,"Thread-73"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41359dc8,peer=0x6481fe98,"Thread-74"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41359dc8,peer=0x64820018,"Thread-75"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41359dc8,peer=0x64820198,"Thread-76"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41359dc8,peer=0x64820318,"Thread-77"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41359dc8,peer=0x64820498,"Thread-78"] attached without supplying a name
I/ActivityManager( 2487): Displayed org.koreader.launcher/.MainActivity: +1s344ms
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41359dc8,peer=0x64820658,"Thread-79"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41359dc8,peer=0x648207d8,"Thread-80"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41359dc8,peer=0x64820b40,"Thread-81"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41359dc8,peer=0x64820de0,"Thread-82"] attached without supplying a name
I/Assets  ( 2893): Skip installation for revision v2024.11
I/KOReader( 2893): has monolibtic? yes
I/KOReader( 2893): lib_search_path: /data/app-lib/org.koreader.launcher-1/?
I/KOReader( 2893): lib_basic_format: lib%s.so
I/KOReader( 2893): lib_version_format: lib%s.so
I/KOReader( 2893): package.loadlib: /data/app-lib/org.koreader.launcher-1/libkoreader-monolibtic.so [libs/libkoreader-lfs]
I/KOReader( 2893): ffi.load: rt.so.1 (RTLD_GLOBAL)
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x4135a398,peer=0x648266c0,"Thread-83"] attached without supplying a name
I/MainActivity( 2893): New intent: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=org.koreader.launcher/.MainActivity }.action
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x4135a398,peer=0x648270e8,"Thread-84"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x4135a398,peer=0x64827268,"Thread-85"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41c18008,peer=0x648273e8,"Thread-86"] attached without supplying a name
I/KOReader( 2893): ffi.findlib: utf8proc [3]
I/KOReader( 2893): ffi.load: /data/app-lib/org.koreader.launcher-1/libkoreader-monolibtic.so
I/KOReader( 2893): ffi.findlib: blitbuffer
I/KOReader( 2893): ffi.load: /data/app-lib/org.koreader.launcher-1/libkoreader-monolibtic.so
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41c18008,peer=0x64827568,"Thread-87"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41c18008,peer=0x648277c0,"Thread-88"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41c18008,peer=0x64827a00,"Thread-89"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41c18008,peer=0x64827c40,"Thread-90"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41c18008,peer=0x64827e68,"Thread-91"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41c18008,peer=0x64828098,"Thread-92"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41c18008,peer=0x648282b8,"Thread-93"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41c18008,peer=0x648284e8,"Thread-94"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41c18008,peer=0x64828728,"Thread-95"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41c18008,peer=0x64828960,"Thread-96"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41c18008,peer=0x64828b98,"Thread-97"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41c18008,peer=0x64828dc0,"Thread-98"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41c18008,peer=0x64828fe8,"Thread-99"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41c18008,peer=0x64829200,"Thread-100"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41c18008,peer=0x648294f8,"Thread-101"] attached without supplying a name
I/KOReader( 2893): Android 4.4.2 - KitKat (API 19) - flavor: rocks
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41c18008,peer=0x64829730,"Thread-102"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41c18008,peer=0x64829968,"Thread-103"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41c18008,peer=0x64829ba0,"Thread-104"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41c18008,peer=0x64829dd8,"Thread-105"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41c18008,peer=0x6482a010,"Thread-106"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41c18008,peer=0x6482a248,"Thread-107"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41c18008,peer=0x6482a480,"Thread-108"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41c18008,peer=0x6482a6b8,"Thread-109"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41c18008,peer=0x6482a8f0,"Thread-110"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41c18008,peer=0x6482ab28,"Thread-111"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41c18008,peer=0x6482aec8,"Thread-112"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41c18008,peer=0x6482b100,"Thread-113"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41c18008,peer=0x6482b338,"Thread-114"] attached without supplying a name
W/System.err( 2893): java.io.FileNotFoundException: /sys/class/backlight/lm3630a_led/color: open failed: EACCES (Permission denied)
W/System.err( 2893):    at libcore.io.IoBridge.open(IoBridge.java:409)
W/System.err( 2893):    at java.io.FileInputStream.<init>(FileInputStream.java:78)
W/System.err( 2893):    at kotlin.io.FilesKt.readText$default(SourceFile:17)
W/System.err( 2893):    at org.koreader.launcher.extensions.FileExtensionsKt.read(SourceFile:6)
W/System.err( 2893):    at org.koreader.launcher.device.lights.TolinoNtxController.getWarmth(SourceFile:19)
W/System.err( 2893):    at org.koreader.launcher.MainActivity.getScreenWarmth(SourceFile:9)
W/System.err( 2893): Caused by: libcore.io.ErrnoException: open failed: EACCES (Permission denied)
W/System.err( 2893):    at libcore.io.Posix.open(Native Method)
W/System.err( 2893):    at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
W/System.err( 2893):    at libcore.io.IoBridge.open(IoBridge.java:393)
W/System.err( 2893):    ... 5 more
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41c18008,peer=0x6482ea38,"Thread-115"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41c18008,peer=0x6482ec70,"Thread-116"] attached without supplying a name
I/KOReader( 2893): initializing for device ntx_6sl
I/KOReader( 2893): framebuffer resolution: {
I/KOReader( 2893):   h = 1680,
I/KOReader( 2893):   w = 1264
I/KOReader( 2893): } --[[table: 0x4416efe8]]
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41c18008,peer=0x6482eea8,"Thread-117"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41c18008,peer=0x6482f0e0,"Thread-118"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41c18008,peer=0x6482f3d8,"Thread-119"] attached without supplying a name
I/KOReader( 2893): ffi.findlib: wrap-mupdf
I/KOReader( 2893): ffi.load: /data/app-lib/org.koreader.launcher-1/libkoreader-monolibtic.so
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41c18008,peer=0x6482f610,"Thread-120"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41c18008,peer=0x6482f848,"Thread-121"] attached without supplying a name
I/KOReader( 2893): ffi.findlib: sqlite3 [0]
I/KOReader( 2893): ffi.load: /data/app-lib/org.koreader.launcher-1/libkoreader-monolibtic.so
I/KOReader( 2893): package.loadlib: /data/app-lib/org.koreader.launcher-1/libkoreader-monolibtic.so [libs/libkoreader-xtext]
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x41360058,peer=0x6482fa80,"Thread-122"] attached without supplying a name
I/KOReader( 2893): ffi.findlib: freetype [6]
I/KOReader( 2893): ffi.load: /data/app-lib/org.koreader.launcher-1/libkoreader-monolibtic.so
I/KOReader( 2893): ffi.findlib: harfbuzz [0]
I/KOReader( 2893): ffi.load: /data/app-lib/org.koreader.launcher-1/libkoreader-monolibtic.so
I/KOReader( 2893): ffi.findlib: zstd [1]
I/KOReader( 2893): ffi.load: /data/app-lib/org.koreader.launcher-1/libkoreader-monolibtic.so
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43bfc750,peer=0x6482fcb8,"Thread-123"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43be9290,peer=0x6482fef0,"Thread-124"] attached without supplying a name
I/KOReader( 2893): package.loadlib: /data/app-lib/org.koreader.launcher-1/libkoreader-monolibtic.so [lpeg]
I/KOReader( 2893): package.loadlib: /data/app-lib/org.koreader.launcher-1/libkoreader-monolibtic.so [libs/libkoreader-nnsvg]
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x648304e8,"Thread-125"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x64830ce0,"Thread-126"] attached without supplying a name
I/KOReader( 2893): Loading plugins from directory: plugins
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x64831418,"Thread-127"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x64831650,"Thread-128"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x64831888,"Thread-129"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x64831ac0,"Thread-130"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x64831cf8,"Thread-131"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x64831f30,"Thread-132"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x64832168,"Thread-133"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x648323a0,"Thread-134"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x648325d8,"Thread-135"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x64832810,"Thread-136"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x64832a48,"Thread-137"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x64832c80,"Thread-138"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x64832eb8,"Thread-139"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x648330f0,"Thread-140"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x64833328,"Thread-141"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x64833560,"Thread-142"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x64833798,"Thread-143"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x648339d0,"Thread-144"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x64833c08,"Thread-145"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x64833e40,"Thread-146"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x64834578,"Thread-147"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x64834cb0,"Thread-148"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x648353e8,"Thread-149"] attached without supplying a name
W/KOReader( 2893): Terminal: Device doesn't meet some of the plugin's requirements
I/KOReader( 2893): package.loadlib: /data/app-lib/org.koreader.launcher-1/libkoreader-monolibtic.so [rapidjson]
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x64835b20,"Thread-150"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x64836258,"Thread-151"] attached without supplying a name
I/KOReader( 2893): Loading plugins from directory: /storage/sdcard1/koreader/plugins/
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x64836490,"Thread-152"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x648366c8,"Thread-153"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x64836900,"Thread-154"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x64836b38,"Thread-155"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x64836d70,"Thread-156"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x64836fa8,"Thread-157"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x648371e0,"Thread-158"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x64837418,"Thread-159"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x64837650,"Thread-160"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x64837888,"Thread-161"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x64837ac0,"Thread-162"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x64837cf8,"Thread-163"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x64837f30,"Thread-164"] attached without supplying a name
W/art     ( 2893): Thread[10,tid=2907,Native,Thread*=0x43d36ab8,peer=0x64838168,"Thread-165"] attached without supplying a name
D/WiFiUtils( 2559): WiFiUtils is wifi enabled false
D/EPubApplication$Applica( 2559): sync ApplicationReceiver broadcast receiver android.intent.action.BATTERY_CHANGED connected false enabled false active false isReadyToPull false isScreenOn true
```
</details>

---

Note: this issue is fixed in `koreader-android-arm-v2024.11-68-g378519ccf_2024-12-12.apk`(current latest nightly), but i am still filing this report as some other users may have the same issue with the `2024.11` release and i couldnt find a existing issue.

**Comment by hasezoey** [comment]
directly closing this again as this issue is fixed in the latest nightly `koreader-android-arm-v2024.11-68-g378519ccf_2024-12-12.apk`
