### ISSUE TITLE
koreader crashing at launch on android 2.3.7

### ISSUE THREAD

**Issue by koAnd** [koreader/koreader#1494]
Hi :)!

The release I'm using is koreader-nightly-20150416.

The crash generates this log entry:
```
Unable to find native library: luajit-launcher
```

Some specs of the hardware and the OS:
```
ro.hardware: v9
ro.build.version.sdk: 10
ro.build.version.codename: [REL
ro.build.version.release: 2.3.7
ro.product.model: V9
ro.product.brand: zte
ro.product.cpu.abi: armeabi-v6l
ro.product.cpu.abi2: armeabi
```

And here is the full log:
```
I/ActivityManager(  223): Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.koreader.launcher/android.app.NativeActivity } from pid 4280
I/ActivityManager(  223): Start proc org.koreader.launcher for activity org.koreader.launcher/android.app.NativeActivity: pid=4849 uid=10052 gids={1015, 3003}
I/WindowManager(  223): Setting rotation to 0, animFlags=1
I/ActivityManager(  223): Config changed: { scale=1.0 imsi=0/0 loc=en_US touch=3 keys=1/1/2 nav=1/1 orien=1 layout=268435492 uiMode=17 seq=27 themeResource=null}
D/szipinf ( 4849): Initializing inflate state
D/AndroidRuntime( 4849): Shutting down VM
W/dalvikvm( 4849): threadid=1: thread exiting with uncaught exception (group=0x40018560)
E/AndroidRuntime( 4849): FATAL EXCEPTION: main
E/AndroidRuntime( 4849): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.koreader.launcher/android.app.NativeActivity}: java.lang.IllegalArgumentException: Unable to find native library: luajit-launcher
E/AndroidRuntime( 4849):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1768)
E/AndroidRuntime( 4849):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1784)
E/AndroidRuntime( 4849):        at android.app.ActivityThread.access$1500(ActivityThread.java:123)
E/AndroidRuntime( 4849):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:939)
E/AndroidRuntime( 4849):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 4849):        at android.os.Looper.loop(Looper.java:130)
E/AndroidRuntime( 4849):        at android.app.ActivityThread.main(ActivityThread.java:3835)
E/AndroidRuntime( 4849):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 4849):        at java.lang.reflect.Method.invoke(Method.java:507)
E/AndroidRuntime( 4849):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
E/AndroidRuntime( 4849):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
E/AndroidRuntime( 4849):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 4849): Caused by: java.lang.IllegalArgumentException: Unable to find native library: luajit-launcher
E/AndroidRuntime( 4849):        at android.app.NativeActivity.onCreate(NativeActivity.java:187)
E/AndroidRuntime( 4849):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
E/AndroidRuntime( 4849):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1722)
E/AndroidRuntime( 4849):        ... 11 more
W/ActivityManager(  223):   Force finishing activity org.koreader.launcher/android.app.NativeActivity
W/SurfaceComposerClient(  223): Destroying surface while a transaction is open. Client 0x3ca988: destroying surface 27, mTransactionOpen=1
W/ActivityManager(  223): Activity pause timeout for HistoryRecord{40714310 org.koreader.launcher/android.app.NativeActivity}
D/HomeLoaders( 4280): aborting loaders
D/dalvikvm( 4280): GC_EXPLICIT freed 126K, 47% free 3514K/6599K, external 2628K/3260K, paused 131ms
D/ViewConsistency( 4280): AbsListView com.android.launcher.AllAppsGridView@4060ee50 enabled= true
D/ViewConsistency( 4280): AbsListView com.android.launcher.AllAppsGridView@4060ee50 enabled= true
D/HomeLoaders( 4280): load applications
D/HomeLoaders( 4280):   --> applications loaded, return
D/HomeLoaders( 4280): loading user items in Thread[main,5,main]
D/HomeLoaders( 4280):   --> items loaded, return
D/HomeLoaders( 4280):   --> loading from cache: 4, 2
D/Launcher( 4280): ------> binding 4 items
D/Launcher( 4280): ------> binding 2 widgets
D/Launcher( 4280): ------> start binding items
D/dalvikvm(  223): GC_EXPLICIT freed 670K, 45% free 5449K/9799K, external 1971K/2295K, paused 109ms
D/dalvikvm( 3590): GC_EXPLICIT freed 227K, 50% free 3256K/6407K, external 551K/1063K, paused 130ms
W/ActivityManager(  223): Activity destroy timeout for HistoryRecord{40714310 org.koreader.launcher/android.app.NativeActivity}
```

**Comment by koAnd** [comment]
I think I know what's wrong,  the release 
```
koreader-nightly-20150416
koreader-android-arm-linux-androideabi-v2014.11-181-g0ccacd7.apk
```
only contains the necessary libs (libluajit-launcher.so, etc) for the armv7 architecture not for armv6 which is what I have.

**Comment by hwhw** [comment]
Oh, right. I'm not sure if we really have sufficient need to build nightlies for generic armeabi... Though it should be possible. But it will needs some changes here and there.

**Comment by chrox** [comment]
Close this now.
