### ISSUE TITLE
Koreader crashes when switching to LANDSCAPE (emulator only)

### ISSUE THREAD

**Issue by tigran123** [koreader/koreader#2201]
* KOReader version: v2015.11-558
* Device: Emulator Ubuntu 16.04 x86_64

#### Issue

If you open a DjVu file and then switch to LANDSCAPE then Koreader crashes like this:

```
./kodev: line 218:  5248 Segmentation fault      EMULATE_READER_W=${screen_width} EMULATE_READER_H=${screen_height} ./reader.lua -d "$args"
```

Stack trace:

```
(gdb) bt
#0  0x00007f3f2f048ca3 in willus_mem_free () from /home/tigran/Kobo/koreader/koreader-emulator-x86_64-linux-gnu/koreader/./libs/libk2pdfopt.so.2
#1  0x00007f3f2f04a6f4 in ocrword_free () from /home/tigran/Kobo/koreader/koreader-emulator-x86_64-linux-gnu/koreader/./libs/libk2pdfopt.so.2
#2  0x00007f3f2f04b2b8 in ocrwords_clear () from /home/tigran/Kobo/koreader/koreader-emulator-x86_64-linux-gnu/koreader/./libs/libk2pdfopt.so.2
#3  0x00007f3f2f03b854 in k2pdfopt_settings_new_source_document_init ()
   from /home/tigran/Kobo/koreader/koreader-emulator-x86_64-linux-gnu/koreader/./libs/libk2pdfopt.so.2
#4  0x00007f3f2f01d109 in k2pdfopt_crop_bmp () from /home/tigran/Kobo/koreader/koreader-emulator-x86_64-linux-gnu/koreader/./libs/libk2pdfopt.so.2
#5  0x0000000000420d64 in ?? ()
#6  0x0000000000445c16 in ?? ()
#7  0x000000000041cc46 in ?? ()
#8  0x000000000041edc7 in ?? ()
#9  0x000000000040e10d in lua_pcall ()
#10 0x000000000040416c in ?? ()
#11 0x0000000000404f8e in ?? ()
#12 0x000000000041edc7 in ?? ()
#13 0x000000000040e187 in lua_cpcall ()
#14 0x0000000000403c84 in main ()
```

**Comment by tigran123** [comment]
Closing this because while testing yesterday I discovered so many different ways to crash koreader on the emulator that it doesn't make sense to consider this particular one as special in any way...
