### ISSUE TITLE
Irregular exit when open a book

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#4322]
* KOReader version: v2018.11.1-9-g5d68076_2018-11-09/  
* Device: KA1

#### Issue
On my KA1 I get irregular exit when trying to open this book: [Tolstoy_ A Russian Life - Rosamund Bartlett.zip](https://github.com/koreader/koreader/files/2568389/Tolstoy_.A.Russian.Life.-.Rosamund.Bartlett.zip)

On my Kobo Aura (KOReader version: v2015.11-1877-g76a3d20_2018-10-11) the book works fine.

What could the problem be?

Thanks!

##### `crash.log` (if applicable)
[crash.log](https://github.com/koreader/koreader/files/2568382/crash.log)

**Comment by poire-z** [comment]
It crashes also on the emulator:
```
LVFormatter::addLine (this=this@entry=0x7fffffffcda0, start=<optimized out>, start@entry=0, end=<optimized out>, x=x@entry=0, para=para@entry=0x5555559fa750, interval=interval@entry=16,
    first=<optimized out>, last=<optimized out>, preFormattedOnly=<optimized out>, needReduceSpace=<optimized out>, isLastPara=<optimized out>)
    at crengine/src/lvtextfm.cpp:1099
1099                        int fh = font->getHeight();
(gdb) backtrace
#0  LVFormatter::addLine (this=this@entry=0x7fffffffcda0, start=<optimized out>, start@entry=0, end=<optimized out>, x=x@entry=0, para=para@entry=0x5555559fa750, interval=interval@entry=16,
    first=<optimized out>, last=<optimized out>, preFormattedOnly=<optimized out>, needReduceSpace=<optimized out>, isLastPara=<optimized out>)
    at crengine/src/lvtextfm.cpp:1099
#1  0x00007fffebd78481 in LVFormatter::processParagraph (this=this@entry=0x7fffffffcda0, start=0, end=end@entry=2, isLastPara=<optimized out>)
    at crengine/src/lvtextfm.cpp:1594
#2  0x00007fffebd75194 in LVFormatter::splitParagraphs (this=0x7fffffffcda0) at crengine/src/lvtextfm.cpp:1617
#3  LVFormatter::format (this=0x7fffffffcda0) at crengine/src/lvtextfm.cpp:1645
#4  LFormattedText::Format (this=0x55555605b6b0, width=width@entry=548, page_height=page_height@entry=578)
    at crengine/src/lvtextfm.cpp:1680
```

It's just before the vertical align code I added recently, so it's probably related... and might explain why it works on your older version. I'll look at it.

**Comment by poire-z** [comment]
The fix will probably not make it in tomorrow's nightly, but in a next one.
