### ISSUE TITLE
koreader crashes when I try to connect to calibre

### ISSUE THREAD

**Issue by Masacroso** [koreader/koreader#6485]
* KOReader version: v2020.07.1
* Device: kobo forma version 4.2215190

#### Issue

Trying to connect calibre with koreader then koreader crashes after I choose any folder in /mnt/onboard

#### Steps to reproduce

Open calibre (Im using version 4.22 of calibre in kubuntu 20.04), then initiate wireless connection with default settings. Now, in kobo forma, open koreader and go to settings, calibre, connect. Then Im asked to select a folder with a long touch, when I select any folder in the file explorer of koreader inside /mnt/onboard then koreader crashes and calibre gives the following error log:

```
Device responded with incorrect information

Traceback (most recent call last):
  File "site-packages/calibre/gui2/device.py", line 90, in run
  File "site-packages/calibre/gui2/device.py", line 473, in _get_device_information
  File "site-packages/calibre/devices/smart_device_app/driver.py", line 50, in _synchronizer
  File "site-packages/calibre/devices/smart_device_app/driver.py", line 1235, in get_device_information
  File "site-packages/calibre/devices/smart_device_app/driver.py", line 50, in _synchronizer
  File "site-packages/calibre/devices/smart_device_app/driver.py", line 648, in _call_client
  File "site-packages/calibre/devices/smart_device_app/driver.py", line 690, in _receive_from_client
ControlError: Device responded with incorrect information
```
Im not sure if I must select some specific folder?

##### `crash.log` (if applicable)

The following is the crash.log located in .ads/koreader

```
riginal fb rotation is set @ 3
Original fb bitdepth is set @ 32bpp
Switching fb bitdepth to 8bpp & rotation to Portrait
[FBInk] Detected a Kobo Forma (377 => Frost @ Mark 7)
Variable fb info: 1440x1920 (1440x1920), 32bpp @ rotation: 3 (Counter Clockwise, 270°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 11796480 bytes & line length: 5760 bytes
Device's expected Portrait orientation should be: 3 (Counter Clockwise, 270°)!

Current rotation is already 3!

Switching fb to 8bpp @ rotation 3 . . .
Setting bitdepth to 8bpp
Setting grayscale to 1
Setting rotate to 3 (Counter Clockwise, 270°)
Setting rotate to 1 (Clockwise, 90°) to account for kernel rotation quirks
Bitdepth is now 8bpp (grayscale: 1) @ rotate: 3 (Counter Clockwise, 270°)

Variable fb info: 1440x1920 (1440x3840), 8bpp @ rotation: 3 (Counter Clockwise, 270°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 11796480 bytes & line length: 1440 bytes
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 08/08/20-03:39:24
 [*] Version: v2020.07.1

ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so.0
ffi.load (warning): libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
SDL2 not loaded:	./setupkoenv.lua:27: Not able to load dynamic library: libSDL2-2.0.so.0
ffi.load: blitbuffer
FB: computed size: 5529600
FB: id           : mxc_epdc_fb
FB: smem_len     : 11796480
FB: line_length  : 1440
FB: xres         : 1440
FB: xres_virtual : 1440
FB: yres         : 1920
FB: yres_virtual : 3840
FB: bpp          : 8
08/08/20-03:39:24 INFO  initializing for device Kobo_frost
08/08/20-03:39:24 INFO  framebuffer resolution: {
    ["h"] = 1920,
    ["w"] = 1440
}
[ko-input] Forked off fake event generator(pid:2679).
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
PING 192.168.1.1 (192.168.1.1): 56 data bytes
64 bytes from 192.168.1.1: seq=0 ttl=64 time=9.292 ms

--- 192.168.1.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 9.292/9.292/9.292 ms
08/08/20-03:39:25 INFO  Loading plugins from directory: plugins
ffi.load: sqlite3
ffi.load: z
ffi.load: sqlite3
08/08/20-03:39:25 INFO  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
08/08/20-03:39:25 INFO  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
08/08/20-03:39:25 INFO  FM loaded plugin SSH at plugins/SSH.koplugin
08/08/20-03:39:25 INFO  FM loaded plugin autosuspend at plugins/autosuspend.koplugin
08/08/20-03:39:25 INFO  FM loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
08/08/20-03:39:25 INFO  FM loaded plugin batterystat at plugins/batterystat.koplugin
08/08/20-03:39:25 INFO  FM loaded plugin calibre at plugins/calibre.koplugin
08/08/20-03:39:25 INFO  FM loaded plugin coverbrowser at plugins/coverbrowser.koplugin
08/08/20-03:39:25 INFO  FM loaded plugin docsettingtweak at plugins/docsettingtweak.koplugin
08/08/20-03:39:25 INFO  FM loaded plugin evernote at plugins/evernote.koplugin
08/08/20-03:39:25 INFO  FM loaded plugin goodreads at plugins/goodreads.koplugin
08/08/20-03:39:25 INFO  FM loaded plugin keepalive at plugins/keepalive.koplugin
08/08/20-03:39:25 INFO  FM loaded plugin movetoarchive at plugins/movetoarchive.koplugin
08/08/20-03:39:25 INFO  FM loaded plugin newsdownloader at plugins/newsdownloader.koplugin
08/08/20-03:39:25 INFO  FM loaded plugin perceptionexpander at plugins/perceptionexpander.koplugin
08/08/20-03:39:25 INFO  FM loaded plugin profiles at plugins/profiles.koplugin
08/08/20-03:39:25 INFO  FM loaded plugin readtimer at plugins/readtimer.koplugin
08/08/20-03:39:25 INFO  FM loaded plugin send2ebook at plugins/send2ebook.koplugin
08/08/20-03:39:25 INFO  FM loaded plugin statistics at plugins/statistics.koplugin
08/08/20-03:39:25 INFO  FM loaded plugin systemstat at plugins/systemstat.koplugin
08/08/20-03:39:25 INFO  FM loaded plugin terminal at plugins/terminal.koplugin
08/08/20-03:39:25 INFO  FM loaded plugin texteditor at plugins/texteditor.koplugin
08/08/20-03:39:25 INFO  FM loaded plugin timesync at plugins/timesync.koplugin
08/08/20-03:39:25 INFO  FM loaded plugin wallabag at plugins/wallabag.koplugin
08/08/20-03:40:15 INFO  set inbox directory /mnt/onboard/matemáticas
ffi.load: libs/libczmq.so.1
ffi.load: libs/libzmq.so.4
ffi.load: libs/libczmq.so.1
08/08/20-03:40:16 WARN  connect to endpoint tcp://192.168.1.48:9090
08/08/20-03:40:16 INFO  connected to calibre 192.168.1.48 9090
./luajit: plugins/calibre.koplugin/metadata.lua:86: bad argument #2 to 'dump' (string expected, got nil)
stack traceback:
	[C]: in function 'dump'
	plugins/calibre.koplugin/metadata.lua:86: in function 'saveDeviceInfo'
	plugins/calibre.koplugin/wireless.lua:428: in function 'setCalibreInfo'
	plugins/calibre.koplugin/wireless.lua:296: in function 'onReceiveJSON'
	plugins/calibre.koplugin/wireless.lua:131: in function 'receiveCallback'
	frontend/ui/message/streammessagequeue.lua:78: in function '(for generator)'
	frontend/ui/uimanager.lua:1129: in function 'processZMQs'
	frontend/ui/uimanager.lua:1159: in function 'handleInput'
	frontend/ui/uimanager.lua:1227: in function 'run'
	./reader.lua:299: in main chunk
	[C]: at 0x00014131
!!!!
Uh oh, something went awry... (Crash n°1: 08/08/20 @ 03:40:17)
Running FW 4.22.15190 on Linux 4.1.15-00286-g2a6a4cb08c66 (#80 SMP PREEMPT Fri Dec 27 17:09:34 CST 2019)
Attempting to restart KOReader . . .
!!!!
```

**Comment by Galunid** [comment]
I think it happens if you don't set Inbox directory prior to trying to connect.
Try this `Calibre -> Wireless Settings -> Set Inbox Directory`, set where you want your books saved. You should be able to connect.

**Comment by Masacroso** [comment]
> I think it happens if you don't set Inbox directory prior to trying to connect.
> Try this `Calibre -> Wireless Settings -> Set Inbox Directory`, set where you want your books saved. You should be able to connect.

Thank you very much, this solved the issue but I think I will have this bug as "open" to be solved in the next version of the plugin. Anyway if some maintainer thinks that it is better to give this question closed is free to close this thread.
