### ISSUE TITLE
Calibre Plugin: "Cannot connect to calibre server"

### ISSUE THREAD

**Issue by shuesken** [koreader/koreader#7210]
* KOReader version: 2021.01
* Device: Kindle PW1

#### Issue
After setting the correct port and IP address, pressing "Connect" yields the error "Cannot connect to calibre server" on a fresh install of KOReader with a current version of Calibre on a local network that does not otherwise prevent connections to that server.

#### Steps to reproduce
Install current version of Calibre. Install current version of KOReader. Start a wireless connection in Calibre. Set the IP and port in KOReader, press "Connect". Wait for error.

#### Additional Information
The calibre server runs on 192.168.178.20:9090. `ping -c1 192.168.178.20` always succeeds from the reader. `nc 192.168.178.20 9090` _sometimes_ prints an empty line and _sometimes_ returns the desired outcome:
```
nc 192.168.178.20 9090

838[9, {"serverProtocolVersion": 1, "validExtensions": ["lrf", "rar", "zip", "rtf", "lit", "txt", "txtz", "text", "htm", "xhtm", "html", "htmlz", "xhtml", "pdf", "pdb", "updb", "pdr", "prc", "mobi", "azw", "doc", "epub", "fb2", "fbz", "djv", "djvu", "lrx", "cbr", "cbz", "cbc", "oebzip", "rb", "imp", "odt", "chm", "tpz", "azw1", "pml", "pmlz", "mbp", "tan", "snb", "xps", "oxps", "azw4", "book", "zbf", "pobi", "docx", "docm", "md", "textile", "markdown", "ibook", "ibooks", "iba", "azw3", "ps", "kepub", "kfx", "kpf"], "passwordChallenge": "", "currentLibraryName": "calibreLibrary", "currentLibraryUUID": "2ff51431-1b10-445e-a031-6aed809352d9", "pubdateFormat": "MMM yyyy", "timestampFormat": "dd MMM yyyy", "lastModifiedFormat": "dd MMM yyyy", "calibre_version": [5, 9, 0], "canSupportUpdateBooks": true, "canSupportLpathChanges": true}]
```
When trying to connect to the server via a browser from the same computer or a different device on the same network, the connection often takes a long time. Usually, the debug from calibre is empty, but I _once_ managed to get this debug log:
```
calibre Debug log
calibre 5.9  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.2.0', 'Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
calibre 5.9  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.2.0', 'Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 125.50000188482092 x 125.50000188482092
Using calibre Qt style: True
[0.00] Starting up...
[0.08] Showing splash screen...
[0.35] splash screen shown
[0.35] Initializing db...
[0.43] db initialized
[0.43] Constructing main UI...
[1.62] main UI initialized...
[1.62] Hiding splash screen
Starting QuickView
Traceback (most recent call last):
  File "calibre/devices/smart_device_app/driver.py", line 652, in _call_client
  File "calibre/devices/smart_device_app/driver.py", line 694, in _receive_from_client
calibre.devices.errors.ControlError: Device responded with incorrect information
Traceback (most recent call last):
  File "calibre/gui2/device.py", line 297, in detect_device
  File "calibre/devices/smart_device_app/driver.py", line 50, in _synchronizer
  File "calibre/devices/smart_device_app/driver.py", line 1054, in open
  File "calibre/devices/smart_device_app/driver.py", line 50, in _synchronizer
  File "calibre/devices/smart_device_app/driver.py", line 652, in _call_client
  File "calibre/devices/smart_device_app/driver.py", line 694, in _receive_from_client
calibre.devices.errors.ControlError: Device responded with incorrect information
[24.90] splash screen hidden
[24.91] Started up in 24.91 seconds with 317 books
SMART_DEV (   0.00:  0.002) _attach_to_port try ip address "" on port 9090
SMART_DEV (   0.95:  0.822) _startup_on_demand listening on port 9090
SMART_DEV (   0.98:  0.001) _attach_to_port try ip address "" on port 54982
SMART_DEV (   1.00:  0.000) _startup_on_demand broadcast socket listening on port 54982
SMART_DEV (   2.04:  1.015) run All IP addresses {'lo0': [{'addr': '127.0.0.1', 'netmask': '255.0.0.0', 'peer': '127.0.0.1'}], 'en0': [{'addr': '192.168.178.20', 'netmask': '255.255.255.0', 'broadcast': '192.168.178.255'}]}
SMART_DEV (  43.22: 41.168) run attempt to open device socket
SMART_DEV (  45.13:  1.910) open
SMART_DEV (  45.15:  0.001) _call_client GET_INITIALIZATION_INFO wfr True
SMART_DEV (  45.16:  0.000) _receive_from_client protocol error -- empty json string
SMART_DEV (  45.17:  0.000) _call_client other exception
SMART_DEV (  45.18:  0.000) _write_metadata_cache
SMART_DEV (  45.19:  0.000) _write_metadata_cache wrote 0 entries, purged 0 entries
Error while trying to open <calibre.devices.smart_device_app.driver.SMART_DEVICE_APP object at 0x110f30130> (Driver: <calibre.devices.smart_device_app.driver.SMART_DEVICE_APP object at 0x110f30130>)
```
Usually the log stops with `Starting QuickView`. Issue occurs with both Calibre 5.9.0 and 5.10.1.

**Comment by pazos** [comment]
Can't reproduce on the emulator or with my device. Both working fine in both auto discovery and manual mode.

Please attach a debug log of KOReader. Since calibre is very very very verbose you might want to tweak https://github.com/koreader/koreader/blob/master/platform/kindle/koreader.sh#L305 to, at least the double.

Also, try to reproduce creating a new empty folder and setting that to the wireless inbox. I usually have a single dir that I test with the 3 drivers available for my device (Bq, connect to folder and wireless driver) but I have no idea how well it works if one transfers books using the Kobo/Kindle.. usb driver and then sets that folder as the wireless inbox (It should prompt you asking you need to be sure you know what you're doing anyways).

**Comment by NiLuJe** [comment]
Yeah, on my end, if nc is reliable, KOReader/UNCaGED are, too.

(That's a slight hint that something may be rotten in the state of Denmark^Wyour network ;p).

**Comment by shuesken** [comment]
This worked today after I set an inbox folder. Thank you for the support and building this software!
