### ISSUE TITLE
KOReader crashes at startup on Tolino Vision if no external mircoSD card is present

### ISSUE THREAD

**Issue by DonKult** [koreader/koreader#8355]
* KOReader version: 2021.10.1
* Device: tolino vision 1 (2014) with up-to-date firmware 14.2.0 (based on Android 4.4.2)

#### Issue

The first edition of the tolino vision line has pretty much the same hardware as its various newer cousins and hence can use the same firmware, except one small hardware difference: It has an external mircoSD card slot to extend the storage which later devices dropped (in favor of waterproof I guess).

koreader crashes on startup if no card is in this slot with

<details>
  <summary>Invalid mkdirs path: /mnt/media_rw/extsd/Android/data/org.koreader.launcher/files/</summary>
<pre>
exception: java.lang.SecurityException
exceptionMessage: Invalid mkdirs path: /mnt/media_rw/extsd/Android/data/org.koreader.launcher/files/
stackTrace: java.lang.RuntimeException: Unable to get provider androidx.core.content.FileProvider: java.lang.SecurityException: Invalid mkdirs path: /mnt/media_rw/extsd/Android/data/org.koreader
.launcher/files/
        at android.app.ActivityThread.installProvider(ActivityThread.java:4793)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4385)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4325)
        at android.app.ActivityThread.access$1500(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.SecurityException: Invalid mkdirs path: /mnt/media_rw/extsd/Android/data/org.koreader.launcher/files/
        at android.os.Parcel.readException(Parcel.java:1465)
        at android.os.Parcel.readException(Parcel.java:1419)
        at android.os.storage.IMountService$Stub$Proxy.mkdirs(IMountService.java:750)
        at android.app.ContextImpl.ensureDirsExistOrFilter(ContextImpl.java:2162)
        at android.app.ContextImpl.getExternalFilesDirs(ContextImpl.java:856)
        at android.content.ContextWrapper.getExternalFilesDirs(ContextWrapper.java:215)
        at androidx.core.content.ContextCompat$Api19Impl.getExternalFilesDirs(ContextCompat.java:1)
        at androidx.core.content.ContextCompat.getExternalFilesDirs(ContextCompat.java:2)
        at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:19)
        at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:3)
        at androidx.core.content.FileProvider.attachInfo(FileProvider.java:4)
        at android.app.ActivityThread.installProvider(ActivityThread.java:4790)
        ... 12 more

class: android.os.Parcel
file: Parcel.java
method: readException
line: 1465
</pre>
</details>
(The installed tolino crashreporter is maximally useless in the message it shows… I just happened to find a report file in a hidden directory `.reports` on the internal sd a log file this is the relevant excerpt from which made me try inserting an sd card and voila…)

If a card is present it starts and functions normally without touching the card again. It starts with the filebrowser on the internal card and its directories are stored there as well. The card can be removed with no observable effect now. On the card it has just created a few directories:
```
$ find /mnt # (card mounted on my pc)
/mnt/Android
/mnt/Android/data
/mnt/Android/data/org.koreader.launcher
/mnt/Android/data/org.koreader.launcher/files
/mnt/Android/data/org.koreader.launcher/cache
/mnt/Android/obb
/mnt/Android/obb/org.koreader.launcher
```

The same directories are on the internal card btw, equally empty. Everything interesting seems to be on the internal card in /koreader. Apart from this puzzling hurdle koreader seems to work fine on the device for the most part.

I am a bit at a lose at who is at fault here as I just saved the device from the waste bin, so I don't have prior experience with the device, other devices of the family, koreader or Android – but I am happy to experiment! Other apps I sideloaded do not have this issue nor create any directories on the card if present, although I haven't tried a whole lot yet & the lack of koreader mentions in the stacktrace make me nervous, so sorry if that turns out to be a firmware issue you can not do anything about.

**Comment by benedikt90** [comment]
If anyone gets sent here: On Tolino shine 2 HD 16.2.0 this is fixed when you reboot the device and disconnect it from USB debugging/mounting.
