### ISSUE TITLE
Joplin Exporter is not working

### ISSUE THREAD

**Issue by ankitmundada** [koreader/koreader#9197]
* KOReader version: 2022.05.1
* Device: Kobo Libra 2 & Koreader for Android Phone (Tried on both)

#### Issue
Joplin Export plugin does not work

#### Steps to reproduce
I've tried exporting notes from the latest koreader update by setting appropriate config of joplin (ip, port & token). It was working properly in the previous build but the latest update has some issues. 

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

Relevant portion from crash.log
```
dhcpcd[4369]: forked to background, child pid 4387
06/11/22-13:44:15 WARN  Cannot reach Joplin server
06/11/22-13:51:03 WARN  Cannot reach Joplin server
06/11/22-14:06:04 INFO  WakeupMgr: scheduling wakeup in 259200
06/11/22-14:06:04 INFO  Inhibiting user input
dhcpcd[4433]: sending signal ARLM to pid 4387
dhcpcd[4433]: waiting for pid 4387 to exit
dhcpcd[4459]: dhcpcd not running
06/11/22-14:06:05 INFO  Kobo Wi-Fi: disabling Wi-Fi
dhcpcd[4471]: dhcpcd not running
Selected interface 'wlan0'
```

<details>
  <summary>crash.log</summary>

```
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 06/09/22-20:13:28
 [*] Version: v2022.05.1

ffi.load: blitbuffer
06/09/22-20:13:28 INFO  initializing for device Kobo_io
06/09/22-20:13:28 INFO  framebuffer resolution: {
    ["h"] = 1680,
    ["w"] = 1264,
}
[ko-input] Forked off fake event generator (pid: 3593)
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libharfbuzz.so.0
ffi.load: libs/libzstd.so.1
ffi.load: libs/libutf8proc.so.2
06/09/22-20:13:29 INFO  Loading plugins from directory: plugins
ffi.load: sqlite3
06/09/22-20:13:35 INFO  GestureDetector:probeClockSource: Touch event timestamps appear to use CLOCK_REALTIME
06/09/22-20:13:35 INFO  opening file /mnt/onboard/kfmon.png
ffi.load: libs/liblept.so.5
ffi.load: libs/libk2pdfopt.so.2
06/09/22-20:13:36 INFO  setting zoom mode to pagewidth
GET https://sync.koreader.rocks:443/syncs/progress/7b06a6162b85ca141ad859d1ebcf11c4
host or service not provided, or not known
PUT https://sync.koreader.rocks:443/syncs/progress
host or service not provided, or not known
06/09/22-20:13:46 INFO  opening file /mnt/onboard/Carnegie, Dale/How to Win Friends and Influence People in the Digital Age - Dale Carnegie.kepub.epub
GET https://sync.koreader.rocks:443/syncs/progress/a1c0f4fefa6ec146c39628f6a969f0f9
host or service not provided, or not known
PUT https://sync.koreader.rocks:443/syncs/progress
host or service not provided, or not known
06/09/22-20:13:49 INFO  WakeupMgr: scheduling wakeup in 259200
06/09/22-20:13:50 INFO  Inhibiting user input
06/09/22-20:14:05 INFO  Kobo suspend: going to sleep . . .
06/09/22-20:14:05 INFO  Kobo suspend: successfully asked the kernel to put subsystems to sleep
06/09/22-20:14:07 INFO  Kobo suspend: waited for 2s because of reasons...
06/09/22-20:14:07 INFO  Kobo suspend: synced FS
06/09/22-20:14:07 INFO  Kobo suspend: asking for a suspend to RAM . . .
06/09/22-20:19:39 INFO  Kobo suspend: ZzZ ZzZ ZzZ... And woke up!
06/09/22-20:19:39 INFO  Kobo resume: clean up after wakeup
06/09/22-20:19:39 INFO  Kobo resume: successfully asked the kernel to resume subsystems
06/09/22-20:19:39 INFO  Restoring user input handling
PUT https://sync.koreader.rocks:443/syncs/progress
host or service not provided, or not known
06/09/22-20:19:39 INFO  WakeupMgr: scheduling wakeup in 259200
06/09/22-20:19:39 INFO  Inhibiting user input
GET https://sync.koreader.rocks:443/syncs/progress/a1c0f4fefa6ec146c39628f6a969f0f9
host or service not provided, or not known
06/09/22-20:19:40 INFO  Kobo resume: clean up after wakeup
06/09/22-20:19:40 INFO  Kobo resume: successfully asked the kernel to resume subsystems
06/09/22-20:19:40 INFO  Restoring user input handling
GET https://sync.koreader.rocks:443/syncs/progress/a1c0f4fefa6ec146c39628f6a969f0f9
host or service not provided, or not known
06/09/22-20:19:43 INFO  GestureDetector:probeClockSource: Touch event timestamps appear to use CLOCK_REALTIME
06/09/22-20:20:18 INFO  Kobo Wi-Fi: enabling Wi-Fi
dhcpcd[3675]: dhcpcd not running
dhcpcd[3682]: version 6.6.6 starting
dhcpcd[3682]: wlan0: using /sys hwaddr: 58:b0:d4:97:26:19
dhcpcd[3682]: wlan0: executing `/libexec/dhcpcd-run-hooks' PREINIT
dhcpcd[3682]: wlan0: executing `/libexec/dhcpcd-run-hooks' NOCARRIER
dhcpcd[3682]: wlan0: waiting for carrier
dhcpcd[3682]: wlan0: carrier acquired
dhcpcd[3682]: wlan0: executing `/libexec/dhcpcd-run-hooks' CARRIER
dhcpcd[3682]: wlan0: delaying IPv4 for 0.4 seconds
dhcpcd[3682]: wlan0: using ClientID 01:58:b0:d4:97:26:19
dhcpcd[3682]: wlan0: soliciting a DHCP lease
dhcpcd[3682]: wlan0: sending DISCOVER (xid 0xc93638eb), next in 3.2 seconds
dhcpcd[3682]: wlan0: acknowledged 192.168.185.178 from 192.168.185.119
dhcpcd[3682]: wlan0: leased 192.168.185.178 for 3600 seconds
dhcpcd[3682]: wlan0: renew in 1800 seconds, rebind in 3150 seconds
dhcpcd[3682]: wlan0: writing lease `/var/db/dhcpcd-wlan0-Ankit.lease'
dhcpcd[3682]: wlan0: adding IP address 192.168.185.178/24
dhcpcd[3682]: wlan0: adding route to 192.168.185.0/24
dhcpcd[3682]: wlan0: adding default route via 192.168.185.119
dhcpcd[3682]: wlan0: executing `/libexec/dhcpcd-run-hooks' BOUND
dhcpcd[3682]: forking to background
dhcpcd[3682]: forked to background, child pid 3707
06/09/22-20:20:32 WARN  Cannot reach Joplin server
06/09/22-20:21:22 WARN  Cannot reach Joplin server
06/09/22-20:22:06 INFO  opening file /mnt/onboard/koreader.png
06/09/22-20:22:07 INFO  setting zoom mode to pagewidth
06/09/22-20:22:23 INFO  WakeupMgr: scheduling wakeup in 259200
06/09/22-20:22:23 INFO  Inhibiting user input
dhcpcd[3733]: sending signal ARLM to pid 3707
dhcpcd[3733]: waiting for pid 3707 to exit
dhcpcd[3758]: dhcpcd not running
06/09/22-20:22:24 INFO  Kobo Wi-Fi: disabling Wi-Fi
dhcpcd[3770]: dhcpcd not running
Selected interface 'wlan0'
OK
06/09/22-20:22:40 INFO  Kobo suspend: going to sleep . . .
06/09/22-20:22:40 INFO  Kobo suspend: successfully asked the kernel to put subsystems to sleep
06/09/22-20:22:42 INFO  Kobo suspend: waited for 2s because of reasons...
06/09/22-20:22:42 INFO  Kobo suspend: synced FS
06/09/22-20:22:42 INFO  Kobo suspend: asking for a suspend to RAM . . .
06/09/22-20:24:10 INFO  Kobo suspend: ZzZ ZzZ ZzZ... And woke up!
06/09/22-20:24:10 INFO  Kobo resume: clean up after wakeup
06/09/22-20:24:10 INFO  Kobo resume: successfully asked the kernel to resume subsystems
06/09/22-20:24:10 INFO  Restoring user input handling
06/09/22-20:24:19 INFO  WakeupMgr: scheduling wakeup in 259200
06/09/22-20:24:19 INFO  Inhibiting user input
06/09/22-20:24:32 INFO  Kobo resume: clean up after wakeup
06/09/22-20:24:32 INFO  Kobo resume: successfully asked the kernel to resume subsystems
06/09/22-20:24:34 INFO  Restoring user input handling
06/09/22-20:24:49 INFO  WakeupMgr: scheduling wakeup in 259200
06/09/22-20:24:49 INFO  Inhibiting user input
06/09/22-20:24:52 INFO  Kobo resume: clean up after wakeup
06/09/22-20:24:52 INFO  Kobo resume: successfully asked the kernel to resume subsystems
06/09/22-20:24:52 INFO  Restoring user input handling
06/09/22-20:25:23 INFO  WakeupMgr: scheduling wakeup in 259200
06/09/22-20:25:23 INFO  Inhibiting user input
06/09/22-20:25:38 INFO  Kobo suspend: going to sleep . . .
06/09/22-20:25:38 INFO  Kobo suspend: successfully asked the kernel to put subsystems to sleep
06/09/22-20:25:40 INFO  Kobo suspend: waited for 2s because of reasons...
06/09/22-20:25:40 INFO  Kobo suspend: synced FS
06/09/22-20:25:40 INFO  Kobo suspend: asking for a suspend to RAM . . .
06/09/22-20:26:22 INFO  Kobo suspend: ZzZ ZzZ ZzZ... And woke up!
06/09/22-20:26:22 INFO  Kobo resume: clean up after wakeup
06/09/22-20:26:22 INFO  Kobo resume: successfully asked the kernel to resume subsystems
06/09/22-20:26:23 INFO  Restoring user input handling
06/09/22-20:28:03 INFO  WakeupMgr: scheduling wakeup in 259200
06/09/22-20:28:03 INFO  Inhibiting user input
06/09/22-20:28:03 INFO  Kobo resume: clean up after wakeup
06/09/22-20:28:03 INFO  Kobo resume: successfully asked the kernel to resume subsystems
06/09/22-20:28:03 INFO  Restoring user input handling
06/09/22-20:28:12 INFO  GestureDetector:probeClockSource: Touch event timestamps appear to use CLOCK_REALTIME
06/09/22-20:28:52 INFO  opening file /mnt/onboard/Carnegie, Dale/How to Win Friends and Influence People in the Digital Age - Dale Carnegie.kepub.epub
GET https://sync.koreader.rocks:443/syncs/progress/a1c0f4fefa6ec146c39628f6a969f0f9
host or service not provided, or not known
06/09/22-20:29:46 INFO  Kobo Wi-Fi: enabling Wi-Fi
dhcpcd[3896]: dhcpcd not running
dhcpcd[3903]: version 6.6.6 starting
dhcpcd[3903]: wlan0: using /sys hwaddr: 58:b0:d4:97:26:19
dhcpcd[3903]: wlan0: executing `/libexec/dhcpcd-run-hooks' PREINIT
dhcpcd[3903]: wlan0: executing `/libexec/dhcpcd-run-hooks' NOCARRIER
dhcpcd[3903]: wlan0: waiting for carrier
dhcpcd[3903]: wlan0: carrier acquired
dhcpcd[3903]: wlan0: executing `/libexec/dhcpcd-run-hooks' CARRIER
dhcpcd[3903]: wlan0: delaying IPv4 for 0.2 seconds
dhcpcd[3903]: wlan0: using ClientID 01:58:b0:d4:97:26:19
dhcpcd[3903]: wlan0: soliciting a DHCP lease
dhcpcd[3903]: wlan0: sending DISCOVER (xid 0x65d47220), next in 4.0 seconds
dhcpcd[3903]: wlan0: acknowledged 192.168.185.178 from 192.168.185.119
dhcpcd[3903]: wlan0: leased 192.168.185.178 for 3599 seconds
dhcpcd[3903]: wlan0: renew in 1799 seconds, rebind in 3149 seconds
dhcpcd[3903]: wlan0: writing lease `/var/db/dhcpcd-wlan0-Ankit.lease'
dhcpcd[3903]: wlan0: adding IP address 192.168.185.178/24
dhcpcd[3903]: wlan0: adding route to 192.168.185.0/24
dhcpcd[3903]: wlan0: adding default route via 192.168.185.119
dhcpcd[3903]: wlan0: executing `/libexec/dhcpcd-run-hooks' BOUND
dhcpcd[3903]: forking to background
dhcpcd[3903]: forked to background, child pid 3928
06/09/22-20:30:00 WARN  Cannot reach Joplin server
06/09/22-20:30:18 WARN  Cannot reach Joplin server
06/09/22-20:30:44 WARN  Cannot reach Joplin server
06/09/22-20:30:54 INFO  WakeupMgr: scheduling wakeup in 259200
06/09/22-20:30:54 INFO  Inhibiting user input
06/09/22-20:30:54 INFO  Kobo resume: clean up after wakeup
06/09/22-20:30:54 INFO  Kobo resume: successfully asked the kernel to resume subsystems
06/09/22-20:30:55 INFO  Restoring user input handling
06/09/22-20:30:56 INFO  WakeupMgr: scheduling wakeup in 259200
06/09/22-20:30:56 INFO  Inhibiting user input
dhcpcd[3955]: sending signal ARLM to pid 3928
dhcpcd[3955]: waiting for pid 3928 to exit
dhcpcd[3980]: dhcpcd not running
06/09/22-20:30:57 INFO  Kobo Wi-Fi: disabling Wi-Fi
dhcpcd[3992]: dhcpcd not running
Selected interface 'wlan0'
OK
GET https://sync.koreader.rocks:443/syncs/progress/a1c0f4fefa6ec146c39628f6a969f0f9
host or service not provided, or not known
06/09/22-20:31:13 INFO  Kobo suspend: going to sleep . . .
06/09/22-20:31:13 INFO  Kobo suspend: successfully asked the kernel to put subsystems to sleep
06/09/22-20:31:15 INFO  Kobo suspend: waited for 2s because of reasons...
06/09/22-20:31:15 INFO  Kobo suspend: synced FS
06/09/22-20:31:15 INFO  Kobo suspend: asking for a suspend to RAM . . .
06/09/22-21:02:18 INFO  Kobo suspend: ZzZ ZzZ ZzZ... And woke up!
06/09/22-21:02:18 INFO  Kobo resume: clean up after wakeup
06/09/22-21:02:18 INFO  Kobo resume: successfully asked the kernel to resume subsystems
06/09/22-21:02:19 INFO  Restoring user input handling
GET https://sync.koreader.rocks:443/syncs/progress/a1c0f4fefa6ec146c39628f6a969f0f9
host or service not provided, or not known
PUT https://sync.koreader.rocks:443/syncs/progress
host or service not provided, or not known
06/09/22-21:02:20 INFO  WakeupMgr: scheduling wakeup in 259200
06/09/22-21:02:20 INFO  Inhibiting user input
06/09/22-21:02:36 INFO  Kobo suspend: going to sleep . . .
06/09/22-21:02:36 INFO  Kobo suspend: successfully asked the kernel to put subsystems to sleep
06/09/22-21:02:38 INFO  Kobo suspend: waited for 2s because of reasons...
06/09/22-21:02:38 INFO  Kobo suspend: synced FS
06/09/22-21:02:38 INFO  Kobo suspend: asking for a suspend to RAM . . .
06/09/22-21:26:32 INFO  Kobo suspend: ZzZ ZzZ ZzZ... And woke up!
06/09/22-21:26:32 INFO  Kobo resume: clean up after wakeup
06/09/22-21:26:32 INFO  Kobo resume: successfully asked the kernel to resume subsystems
06/09/22-21:26:33 INFO  Restoring user input handling
GET https://sync.koreader.rocks:443/syncs/progress/a1c0f4fefa6ec146c39628f6a969f0f9
host or service not provided, or not known
PUT https://sync.koreader.rocks:443/syncs/progress
host or service not provided, or not known
06/09/22-21:26:34 INFO  WakeupMgr: scheduling wakeup in 259200
06/09/22-21:26:34 INFO  Inhibiting user input
06/09/22-21:26:49 INFO  Kobo suspend: going to sleep . . .
06/09/22-21:26:49 INFO  Kobo suspend: successfully asked the kernel to put subsystems to sleep
06/09/22-21:26:52 INFO  Kobo suspend: waited for 2s because of reasons...
06/09/22-21:26:52 INFO  Kobo suspend: synced FS
06/09/22-21:26:52 INFO  Kobo suspend: asking for a suspend to RAM . . .
06/10/22-19:41:32 INFO  Kobo suspend: ZzZ ZzZ ZzZ... And woke up!
06/10/22-19:41:32 INFO  Kobo resume: clean up after wakeup
06/10/22-19:41:32 INFO  Kobo resume: successfully asked the kernel to resume subsystems
06/10/22-19:41:32 INFO  Restoring user input handling
GET https://sync.koreader.rocks:443/syncs/progress/a1c0f4fefa6ec146c39628f6a969f0f9
host or service not provided, or not known
PUT https://sync.koreader.rocks:443/syncs/progress
host or service not provided, or not known
06/10/22-19:56:32 INFO  WakeupMgr: scheduling wakeup in 259200
06/10/22-19:56:32 INFO  Inhibiting user input
06/10/22-19:56:47 INFO  Kobo suspend: going to sleep . . .
06/10/22-19:56:47 INFO  Kobo suspend: successfully asked the kernel to put subsystems to sleep
06/10/22-19:56:49 INFO  Kobo suspend: waited for 2s because of reasons...
06/10/22-19:56:49 INFO  Kobo suspend: synced FS
06/10/22-19:56:49 INFO  Kobo suspend: asking for a suspend to RAM . . .
06/10/22-22:29:27 INFO  Kobo suspend: ZzZ ZzZ ZzZ... And woke up!
PUT https://sync.koreader.rocks:443/syncs/progress
host or service not provided, or not known
06/10/22-22:29:27 INFO  WakeupMgr: scheduling wakeup in 259200
06/10/22-22:29:27 INFO  Kobo resume: clean up after wakeup
06/10/22-22:29:27 INFO  Kobo resume: successfully asked the kernel to resume subsystems
06/10/22-22:29:28 INFO  Restoring user input handling
GET https://sync.koreader.rocks:443/syncs/progress/a1c0f4fefa6ec146c39628f6a969f0f9
host or service not provided, or not known
PUT https://sync.koreader.rocks:443/syncs/progress
host or service not provided, or not known
06/10/22-22:41:27 INFO  WakeupMgr: scheduling wakeup in 259200
06/10/22-22:41:27 INFO  Inhibiting user input
06/10/22-22:41:43 INFO  Kobo suspend: going to sleep . . .
06/10/22-22:41:43 INFO  Kobo suspend: successfully asked the kernel to put subsystems to sleep
06/10/22-22:41:45 INFO  Kobo suspend: waited for 2s because of reasons...
06/10/22-22:41:45 INFO  Kobo suspend: synced FS
06/10/22-22:41:45 INFO  Kobo suspend: asking for a suspend to RAM . . .
06/10/22-22:54:05 INFO  Kobo suspend: ZzZ ZzZ ZzZ... And woke up!
06/10/22-22:54:05 INFO  Kobo resume: clean up after wakeup
06/10/22-22:54:05 INFO  Kobo resume: successfully asked the kernel to resume subsystems
06/10/22-22:54:05 INFO  Restoring user input handling
GET https://sync.koreader.rocks:443/syncs/progress/a1c0f4fefa6ec146c39628f6a969f0f9
host or service not provided, or not known
PUT https://sync.koreader.rocks:443/syncs/progress
host or service not provided, or not known
06/10/22-23:17:15 INFO  WakeupMgr: scheduling wakeup in 259200
06/10/22-23:17:15 INFO  Inhibiting user input
06/10/22-23:17:31 INFO  Kobo suspend: going to sleep . . .
06/10/22-23:17:31 INFO  Kobo suspend: successfully asked the kernel to put subsystems to sleep
06/10/22-23:17:33 INFO  Kobo suspend: waited for 2s because of reasons...
06/10/22-23:17:33 INFO  Kobo suspend: synced FS
06/10/22-23:17:33 INFO  Kobo suspend: asking for a suspend to RAM . . .
06/10/22-23:19:30 INFO  Kobo suspend: ZzZ ZzZ ZzZ... And woke up!
06/10/22-23:19:30 INFO  Kobo resume: clean up after wakeup
06/10/22-23:19:30 INFO  Kobo resume: successfully asked the kernel to resume subsystems
06/10/22-23:19:30 INFO  Restoring user input handling
GET https://sync.koreader.rocks:443/syncs/progress/a1c0f4fefa6ec146c39628f6a969f0f9
host or service not provided, or not known
PUT https://sync.koreader.rocks:443/syncs/progress
host or service not provided, or not known
06/10/22-23:28:19 INFO  WakeupMgr: scheduling wakeup in 259200
06/10/22-23:28:19 INFO  Inhibiting user input
06/10/22-23:28:35 INFO  Kobo suspend: going to sleep . . .
06/10/22-23:28:35 INFO  Kobo suspend: successfully asked the kernel to put subsystems to sleep
06/10/22-23:28:37 INFO  Kobo suspend: waited for 2s because of reasons...
06/10/22-23:28:37 INFO  Kobo suspend: synced FS
06/10/22-23:28:37 INFO  Kobo suspend: asking for a suspend to RAM . . .
06/10/22-23:47:50 INFO  Kobo suspend: ZzZ ZzZ ZzZ... And woke up!
06/10/22-23:47:50 INFO  Kobo resume: clean up after wakeup
06/10/22-23:47:50 INFO  Kobo resume: successfully asked the kernel to resume subsystems
06/10/22-23:47:50 INFO  Restoring user input handling
GET https://sync.koreader.rocks:443/syncs/progress/a1c0f4fefa6ec146c39628f6a969f0f9
host or service not provided, or not known
06/10/22-23:53:33 INFO  GestureDetector:probeClockSource: Touch event timestamps appear to use CLOCK_REALTIME
PUT https://sync.koreader.rocks:443/syncs/progress
host or service not provided, or not known
06/11/22-00:18:16 INFO  WakeupMgr: scheduling wakeup in 259200
06/11/22-00:18:16 INFO  Inhibiting user input
06/11/22-00:18:32 INFO  Kobo suspend: going to sleep . . .
06/11/22-00:18:32 INFO  Kobo suspend: successfully asked the kernel to put subsystems to sleep
06/11/22-00:18:34 INFO  Kobo suspend: waited for 2s because of reasons...
06/11/22-00:18:34 INFO  Kobo suspend: synced FS
06/11/22-00:18:34 INFO  Kobo suspend: asking for a suspend to RAM . . .
06/11/22-11:55:34 INFO  Kobo suspend: ZzZ ZzZ ZzZ... And woke up!
06/11/22-11:55:34 INFO  Kobo resume: clean up after wakeup
06/11/22-11:55:34 INFO  Kobo resume: successfully asked the kernel to resume subsystems
06/11/22-11:55:35 INFO  Restoring user input handling
GET https://sync.koreader.rocks:443/syncs/progress/a1c0f4fefa6ec146c39628f6a969f0f9
host or service not provided, or not known
06/11/22-12:04:20 INFO  GestureDetector:probeClockSource: Touch event timestamps appear to use CLOCK_REALTIME
PUT https://sync.koreader.rocks:443/syncs/progress
host or service not provided, or not known
06/11/22-13:02:47 INFO  WakeupMgr: scheduling wakeup in 259200
06/11/22-13:02:47 INFO  Inhibiting user input
06/11/22-13:03:03 INFO  Kobo suspend: going to sleep . . .
06/11/22-13:03:03 INFO  Kobo suspend: successfully asked the kernel to put subsystems to sleep
06/11/22-13:03:05 INFO  Kobo suspend: waited for 2s because of reasons...
06/11/22-13:03:05 INFO  Kobo suspend: synced FS
06/11/22-13:03:05 INFO  Kobo suspend: asking for a suspend to RAM . . .
06/11/22-13:43:45 INFO  Kobo suspend: ZzZ ZzZ ZzZ... And woke up!
06/11/22-13:43:45 INFO  Kobo resume: clean up after wakeup
06/11/22-13:43:45 INFO  Kobo resume: successfully asked the kernel to resume subsystems
06/11/22-13:43:45 INFO  Restoring user input handling
GET https://sync.koreader.rocks:443/syncs/progress/a1c0f4fefa6ec146c39628f6a969f0f9
host or service not provided, or not known
06/11/22-13:43:49 INFO  GestureDetector:probeClockSource: Touch event timestamps appear to use CLOCK_REALTIME
06/11/22-13:43:58 INFO  Kobo Wi-Fi: enabling Wi-Fi
dhcpcd[4362]: dhcpcd not running
dhcpcd[4369]: version 6.6.6 starting
dhcpcd[4369]: wlan0: using /sys hwaddr: 58:b0:d4:97:26:19
dhcpcd[4369]: wlan0: executing `/libexec/dhcpcd-run-hooks' PREINIT
dhcpcd[4369]: wlan0: executing `/libexec/dhcpcd-run-hooks' CARRIER
dhcpcd[4369]: wlan0: delaying IPv4 for 0.6 seconds
dhcpcd[4369]: wlan0: using ClientID 01:58:b0:d4:97:26:19
dhcpcd[4369]: wlan0: soliciting a DHCP lease
dhcpcd[4369]: wlan0: sending DISCOVER (xid 0x1e06ab48), next in 3.3 seconds
dhcpcd[4369]: wlan0: offered 192.168.0.149 from 192.168.0.1
dhcpcd[4369]: wlan0: sending REQUEST (xid 0x1e06ab48), next in 4.8 seconds
dhcpcd[4369]: wlan0: acknowledged 192.168.0.149 from 192.168.0.1
dhcpcd[4369]: wlan0: leased 192.168.0.149 for 7200 seconds
dhcpcd[4369]: wlan0: renew in 3600 seconds, rebind in 6300 seconds
dhcpcd[4369]: wlan0: writing lease `/var/db/dhcpcd-wlan0-DSR144.lease'
dhcpcd[4369]: wlan0: adding IP address 192.168.0.149/24
dhcpcd[4369]: wlan0: adding route to 192.168.0.0/24
dhcpcd[4369]: wlan0: adding default route via 192.168.0.1
dhcpcd[4369]: wlan0: executing `/libexec/dhcpcd-run-hooks' BOUND
dhcpcd[4369]: forking to background
dhcpcd[4369]: forked to background, child pid 4387
06/11/22-13:44:15 WARN  Cannot reach Joplin server
06/11/22-13:51:03 WARN  Cannot reach Joplin server
06/11/22-14:06:04 INFO  WakeupMgr: scheduling wakeup in 259200
06/11/22-14:06:04 INFO  Inhibiting user input
dhcpcd[4433]: sending signal ARLM to pid 4387
dhcpcd[4433]: waiting for pid 4387 to exit
dhcpcd[4459]: dhcpcd not running
06/11/22-14:06:05 INFO  Kobo Wi-Fi: disabling Wi-Fi
dhcpcd[4471]: dhcpcd not running
Selected interface 'wlan0'
OK
06/11/22-14:06:21 INFO  Kobo suspend: going to sleep . . .
06/11/22-14:06:21 INFO  Kobo suspend: successfully asked the kernel to put subsystems to sleep
06/11/22-14:06:23 INFO  Kobo suspend: waited for 2s because of reasons...
06/11/22-14:06:23 INFO  Kobo suspend: synced FS
06/11/22-14:06:23 INFO  Kobo suspend: asking for a suspend to RAM . . .
06/11/22-14:07:21 INFO  Kobo suspend: ZzZ ZzZ ZzZ... And woke up!
PUT https://sync.koreader.rocks:443/syncs/progress
host or service not provided, or not known
06/11/22-14:07:23 INFO  WakeupMgr: scheduling wakeup in 259200
PUT https://sync.koreader.rocks:443/syncs/progress
host or service not provided, or not known
06/11/22-14:07:30 INFO  WakeupMgr: scheduling wakeup in 259200
06/11/22-14:07:31 INFO  Kobo resume: clean up after wakeup
06/11/22-14:07:31 INFO  Kobo resume: successfully asked the kernel to resume subsystems
06/11/22-14:07:32 INFO  Restoring user input handling
GET https://sync.koreader.rocks:443/syncs/progress/a1c0f4fefa6ec146c39628f6a969f0f9
host or service not provided, or not known
06/11/22-14:07:37 INFO  GestureDetector:probeClockSource: Touch event timestamps appear to use CLOCK_REALTIME
PUT https://sync.koreader.rocks:443/syncs/progress
host or service not provided, or not known
PUT https://sync.koreader.rocks:443/syncs/progress
host or service not provided, or not known
06/11/22-14:07:38 INFO  quitting uimanager

```
</details>

**Comment by pazos** [comment]
It is working as expected. The warning message informs you it cannot reach a Joplin server on the specified ip/port. 

Remember that you need to setup port forwarding each time you need, following https://github.com/koreader/koreader/wiki/Joplin#port-forwarding

**Comment by ankitmundada** [comment]
@pazos 

The server is working fine. I have setup a personal joplin server and hitting its `ping` endpoint works fine. 
Here's the output I get. You can try it on your side as well.

```
➜  ~ curl http://35.202.32.62:22300/ping
JoplinClipperServer
```


I believe, the logic at line 306 in joplin.lua is getting triggered incorrectly due to some reason.
 https://github.com/koreader/koreader/blob/6804b77251431c6c5a3a57ea0e17ef25d8260dca/plugins/exporter.koplugin/target/joplin.lua#L306

**Comment by pazos** [comment]
@ankitmundada: that's great!

I've tried to push an annotation against your server (obviously without a valid token).

It served me to catch a bug but is not related with your issue.
After fixing the bug I get the expected response:

![joplin-failed](https://user-images.githubusercontent.com/975883/173229733-82419d1a-b012-41f2-97ac-e40c59d9359a.png)

And the logs provide a bit more info:

```
06/12/22-12:53:44 WARN  Joplin notebookExist error Invalid "token" parameter: 

Error: Invalid "token" parameter
    at Api.checkToken_ (/root/.joplin-bin/lib/node_modules/joplin/node_modules/@joplin/lib/services/rest/Api.js:185:19)
    at Api.<anonymous> (/root/.joplin-bin/lib/node_modules/joplin/node_modules/@joplin/lib/services/rest/Api.js:148:18)
    at Generator.next (<anonymous>)
    at /root/.joplin-bin/lib/node_modules/joplin/node_modules/@joplin/lib/services/rest/Api.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/root/.joplin-bin/lib/node_modules/joplin/node_modules/@joplin/lib/services/rest/Api.js:4:12)
    at Api.route (/root/.joplin-bin/lib/node_modules/joplin/node_modules/@joplin/lib/services/rest/Api.js:100:16)
    at ClipperServer.<anonymous> (/root/.joplin-bin/lib/node_modules/joplin/node_modules/@joplin/lib/ClipperServer.js:168:58)
    at Generator.next (<anonymous>)
    at /root/.joplin-bin/lib/node_modules/joplin/node_modules/@joplin/lib/ClipperServer.js:8:71
06/12/22-12:53:45 WARN  Joplin notebookExist error Invalid "token" parameter: 

Error: Invalid "token" parameter
    at Api.checkToken_ (/root/.joplin-bin/lib/node_modules/joplin/node_modules/@joplin/lib/services/rest/Api.js:185:19)
    at Api.<anonymous> (/root/.joplin-bin/lib/node_modules/joplin/node_modules/@joplin/lib/services/rest/Api.js:148:18)
    at Generator.next (<anonymous>)
    at /root/.joplin-bin/lib/node_modules/joplin/node_modules/@joplin/lib/services/rest/Api.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/root/.joplin-bin/lib/node_modules/joplin/node_modules/@joplin/lib/services/rest/Api.js:4:12)
    at Api.route (/root/.joplin-bin/lib/node_modules/joplin/node_modules/@joplin/lib/services/rest/Api.js:100:16)
    at ClipperServer.<anonymous> (/root/.joplin-bin/lib/node_modules/joplin/node_modules/@joplin/lib/ClipperServer.js:168:58)
    at Generator.next (<anonymous>)
    at /root/.joplin-bin/lib/node_modules/joplin/node_modules/@joplin/lib/ClipperServer.js:8:71
06/12/22-12:53:46 WARN  Joplin createNotebook error Invalid "token" parameter: 

Error: Invalid "token" parameter
    at Api.checkToken_ (/root/.joplin-bin/lib/node_modules/joplin/node_modules/@joplin/lib/services/rest/Api.js:185:19)
    at Api.<anonymous> (/root/.joplin-bin/lib/node_modules/joplin/node_modules/@joplin/lib/services/rest/Api.js:148:18)
    at Generator.next (<anonymous>)
    at /root/.joplin-bin/lib/node_modules/joplin/node_modules/@joplin/lib/services/rest/Api.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/root/.joplin-bin/lib/node_modules/joplin/node_modules/@joplin/lib/services/rest/Api.js:4:12)
    at Api.route (/root/.joplin-bin/lib/node_modules/joplin/node_modules/@joplin/lib/services/rest/Api.js:100:16)
    at ClipperServer.<anonymous> (/root/.joplin-bin/lib/node_modules/joplin/node_modules/@joplin/lib/ClipperServer.js:168:58)
    at Generator.next (<anonymous>)
    at /root/.joplin-bin/lib/node_modules/joplin/node_modules/@joplin/lib/ClipperServer.js:8:71
06/12/22-12:53:46 WARN  Joplin: unable to create new notebook
```

If I do the same agaisnt my own instance (with a valid token this time) I have no problems to export to joplin.

Please check your device's network connectivity.
